### PR TITLE
Feature/drag drop row to other table

### PR DESCRIPTION
**Pull request by LeanderCoevoet**
## Related Issue
Partially related to this issue: #1219
But expand from this PR: #1995 and  #2011 

## Description
It is now possible to drag and drop from one table to another one. There are 2 actions that can happen you can drag a row from 1 table to another and insert it in between others rows and combine rows. The method for this needs to implemented by your self in the onDropEnd of the DragDropContext. But this is fairly easy and there is an example in the demo.js. To combine rows you need to add the isCombineEnabled: true to the draggableRowsOptions so you will get a filled in combine result from the DragDropContext. For this to be possible there were extra props added.

## Related PRs
List related PRs against other branches: #1995 and  #2011 
I branched of both of those branches so everything would be split in smaller PR.

## Impacted Areas in Application
The drag-drop feature is expanded all original feature should still work.

## Additional Notes
There are more things possible now than only drag and drop to another table. You can make a copy of the Gmail functionality of dragging a mail to a folder. You can get creative with it.

### CODE REVIEW

**Comment by mbrn** [comment]
Please resolve conflicts

**Comment by LeanderCoevoet** [comment]
Resolved conflict and ran prettier

**Comment by mbrn** [comment]
Hi @LeanderCoevoet 

Thanks for your effort. But i can't merge this pr. It contains a lot of changes. We will start to a big refactor, testing progress. So i won't accept big changes on code. We will implement this feature later. Thanks for your understanding.

**Comment by LeanderCoevoet** [comment]
@mbrn Good to know. If anybody is interested in using this feature be my guest.

**Pull request closed without merging**
