### PR TITLE
feat(filter): add checked checkbox filter

### PR DESCRIPTION
**Pull request by balibou**
## Related Issue
#78

## Description
When selecting a row with a checkbox, I would like to filter only selected rows

## Impacted Areas in Application
List general components of the application that this PR will affect:

* m-table-body.js
* m-table-filter-row.js
* material-table.js
* package.json (@material-ui/core in dependencies missing)
* example-options.mdx (for updating demo)

## Additional Notes
Awesome package !

### CODE REVIEW

**Comment by mbrn** [comment]
After i check everything  i will merge this. Thank you @balibou

**Comment by balibou** [comment]
@mbrn hold on I just spotted something I forgot. I will fix it now

**Comment by balibou** [comment]
@mbrn done 😄

**Comment by mbrn** [comment]
Thanks @balibou , I hope that i can merge today

**Comment by balibou** [comment]
@mbrn if you remove material core in package.json there will be an error when doing a yarn

**Comment by mbrn** [comment]
> @mbrn if you remove material core in package.json there will be an error when doing a yarn

Yes but it is peedDependent package. So we wait user already have material-ui/core in their project

**Comment by balibou** [comment]
> I added yarn.lock to .gitignore

you should let it in the repo (best practice), to be sure that everyone that work on the package have the same versions of the dependencies locally

**Comment by mbrn** [comment]
> To me it should work like this:
> 
> Checked: Show only checked rows
> Unchecked: Show all rows (because the filter is not activated)
> Unstable: No state

Yes.  but our current boolean filter works as I mention about.

**Comment by mbrn** [comment]
> > I added yarn.lock to .gitignore
> 
> you should let it in the repo (best practice), to be sure that everyone that work on the package have the same versions of the dependencies locally

I didnt know it is the best practice. I will look at this and add it again.

**Comment by balibou** [comment]
> I didnt know it is the best practice. I will look at this and add it again.

https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by balibou** [comment]
> Yes. but our current boolean filter works as I mention about.

Ok maybe we should change it

**Comment by mbrn** [comment]
Thanks @balibou. I will add yarn.lock again.

**Comment by akshaycj47** [comment]
@balibou @mbrn is it still possible to do this? 
It looks the filter checkbox is replaced by select all checkbox?

**Pull request merged**
