### PR TITLE
onFilterChange not receiving Values Fixed. Trigger Filter on Select or onClose by choice

### PR DESCRIPTION
**Pull request by ashindiano**
## Related Issue
 `#2055`

## Description
onFilterChange was not receiving filteredValues, this bug fixes it.

##Usage
In the Column Definitions, use 
filterOnItemSelect = true , to make the table process the filter on selection
filterOnItemSelect = null/false/undefined means the filter process is initiated on Close event

## Impacted Areas in Application
List general components of the application that this PR will affect:

* MTableFilterRow

## Additional Notes
Since the current version prefers onClose Event to trigger filter process, I did not choose to disturb it.

### CODE REVIEW

**Comment by sankaran-m-k** [comment]
It works fine, tested it +1

**Comment by ashindiano** [comment]
Conflicts resolved...


Also if Merged please update the WEBSITE with the following props under columns section

##columns
# filterOnItemSelect:  (boolean) true = Filter values processed on Item selection, false = Filter values processed after onClose event of dropdown

**Comment by nagaraja-PC** [comment]
It works fine, I have verified.

**Comment by Domino987** [comment]
Can you please resolve the conflicts? Thank you.

**Comment by ashindiano** [comment]
@Domino987, Conflicts resolved

**Comment by ashindiano** [comment]
@Domino987 @mbrn  Could you guys check on the Prettier CLI, Some permission denied issue.

**Pull request merged**
