### PR TITLE
fix: missing width in Column

### PR DESCRIPTION
**Pull request by bluelovers**
## Related Issue
Relate the Github issue with this PR using `#`

## Description
Simple words to describe the overall goals of the pull request's commits.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

## Additional Notes
This is optional, feel free to follow your hearth and write here :)

### CODE REVIEW

**Comment by ifndefdeadmau5** [comment]
This is dupe for #1659 but that one is also not approved yet...

**Comment by seekcx** [comment]
So why not merge this?

**Comment by senser1** [comment]
Yes, merge this please so my `//@ts-ignore` can be removed.

**Comment by Cnordbo** [comment]
@mbrn, could you have a look at this?

**Comment by mbrn** [comment]
Already merged a same pr. Thanks for contribution

**Pull request closed without merging**
