### PR TITLE
Support for a customExport callback function.

### LINKED ISSUE #1318: I want to be able to give a custom function to the component know how to get a value from a column when it want to export data to csv
I have a table that the values are in a nested array, so I need to map this array to values, for this I used the `render` function that can be added on the `columns` property and so I get the values from my nested array and show on the table, but for export with CSV I can't do that, so when the component tries to export to CSV the values, the component doesn't know how to get the values so my CSV is exported empty, I would like to be able to give a custom function as the `render` that the `columns` property has for when the component tries to export my data to CSV it can know how to get the value from the column, with this i can export complex objects that have fields more deeper

I think that the implementation can be something like :

```
const getDataByColumnName = (columnName,rowData) =>  // implement how to get the value of this specific column
```

the solution is simple if this function isn't undefined when the component will export to CSV, it will use this function instead to access directly the value of the raw data.

Maybe I can help with the implementation of this feature

Creating this feature a think will decrease the necessity of implement all the way to export CSV and others will be able to export the data from the table more easier

### LINKED ISSUE #1477: Support for array column type and export csv
**Is your feature request related to a problem? Please describe.**
One the fields I'd like to render is an array field. I currently render the column using a custom render method which works fine. The problem comes form the default export option. When I export it to csv, the array field gets exported with commas in it and no quotation around the value, which the csv interprets as a new column. 
As an example: 
```json
data = [
    { "id": 1, "tags": ["tag1", "tag2"] },
    { "id": 2, "tags": ["tag2",] },
]
```
In the export this comes out as
```csv
"id","tags"
"1",tag1,tag2
"2",tag2
```

For some reason all fields are wrapped with quotation except the array field which can use it the most.

**Describe the solution you'd like**
A quick fix would be to wrap all exported csv cells in quotations (including the array fields) so the csv can be interpreted properly.

Another solution is described in #1318 

In general adding support for array data columns would be nice!

**Describe alternatives you've considered**
An option is to override the `exportCsv` options but that would be too cumbersome for one column.

### LINKED ISSUE #1808: Export to csv displays [object object] for complex data column
When I am trying to export to csv it works fine for simple data but for array of objects it does not export correctly.while i am displaying correctly in table.

### PR DESCRIPTION
**Pull request by mogilvie**
## Related Issue
Fixes #1477, Fixes #1808, Fixes #1318

## Description
Provide a function to transform rowData for export to CSV.

The user would define the customData function in their columnDefinition.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Impacted Areas in Application
List general components of the application that this PR will affect:

*src/components/m-table-toolbar.js

## Additional Notes
Not sure if returning before this.props.getFieldValue is skipping any important features.

### CODE REVIEW

**Comment by Domino987** [comment]
Seems like there are merge conflicts. Can you remove those?

**Comment by mbrn** [comment]
Please resolve conflicts

**Comment by mbrn** [comment]
Closing.

**Comment by hbermani** [comment]
Was this merged into Master, unable to access customExport in column?

**Comment by DominikEngel** [comment]
No it was not because the merge conflicts were not fixed. If those are resolved, it can be reopened.

**Comment by hbermani** [comment]
Thank you @DominikEngel , I am not familiar with the code base but happy to try and help if there are some pointers. @mogilvie  & @Domino987 do you recall what was causing the merge conflict? It would be good to get this resolved as expect many will benefit from this feature.

**Comment by mogilvie** [comment]
No time to resolve merge conflicts at the moment. Working off own fork for now. I'll leave this here if anyone else wants to resolve conflicts or implement the changes themselves.

**Comment by hbermani** [comment]
Appreciate your help with this @Domino987 .

**Review by Domino987 — APPROVED** [review]

**Comment by Domino987** [comment]
@hbermani @mogilvie Once this is merged, can you create a PR to update the docs?

**Comment by hbermani** [comment]
> @hbermani @mogilvie Once this is merged, can you create a PR to update the docs?

I'll happily give that a go.

**Comment by iortega-dev** [comment]
Hello, how is this PR going?
I'm eager to use this functionality 👍

**Comment by hbermani** [comment]
Just wondering how this PR is progressing. Do we know what's blocking it from progressing and what help is needed?

**Comment by mogilvie** [comment]
I'm not that familiar with the Prettier CLI process, but it looks like an error in the configuration of the Prettier CLI

> /entrypoint.sh: line 9: GITHUB_TOKEN: parameter not set
Commiting and pushing changes...
M	src/components/m-table-toolbar.js
Your branch is up to date with 'origin/master'.
[master 7ff283e] Prettified Code!
 Author: Domino987 <Domino987@users.noreply.github.com>
 1 file changed, 8 insertions(+), 3 deletions(-)
**remote: Permission to mbrn/material-table.git denied to github-actions[bot]**.
fatal: unable to access 'https://github.com/mbrn/material-table/': The requested URL returned error: 403

**Comment by mogilvie** [comment]
Yes, the Prettier is failing everything at the moment [https://github.com/mbrn/material-table/actions](https://github.com/mbrn/material-table/actions)
Who has authority to sort that out?

**Comment by FearghalCampbellPB** [comment]
Also interested in this PR. Would clear up a number of open issues.

**Comment by iortega-dev** [comment]
@Domino987 did you checked what conflicts are happening to this PR?

**Comment by iortega-dev** [comment]
@mbrn is there something I could do for help?

**Comment by Domino987** [comment]
@iortega-dev there are no conflicts. Nobody Approved it they and the prettier cli fails which is currently expected.

**Review by Domino987 — APPROVED** [review]
Looks good to me

**Comment by cmccann702** [comment]
Will this be merged into latest? Can no longer see the logs as to why it failed

**Comment by mogilvie** [comment]
It's the prettier CLI which is failing

> @iortega-dev there are no conflicts. Nobody Approved it they and the prettier cli fails which is currently expected.

**Comment by Domino987** [comment]
Due to mbrns absence can you move this pr here so we can get it merged into the new project: https://github.com/material-table-core/core

**Comment by hbermani** [comment]
Good morning, just wondering if anyone managed to work around the Prettier CLI issue for this one. Alternatively, if there is a work around?

**Comment by mogilvie** [comment]
No workaround.
@Domino987 has opened an alterternate repo, and requested I move the PR to that repo.
Only I can't do that as I already have a fork of this repo that I use for a production application, so need to keep. And github won't let me fork both this and the alternate repo.

**Comment by hbermani** [comment]
> No workaround.
> @Domino987 has opened an alterternate repo, and requested I move the PR to that repo.
> Only I can't do that as I already have a fork of this repo that I use for a production application, so need to keep. And github won't let me fork both this and the alternate repo.

I am not familiar with all the Ins and Outs of github but happy to help... Is it something I can do? Would appreciate if there is any Docs around how to do that.

**Comment by Domino987** [comment]
@hbermani what you could do is, fork the new repo material-table-core, apply the changes from this PR to the fork and create a PR to the new repo. Thank you for the help

**Comment by hbermani** [comment]
> @hbermani what you could do is, fork the new repo material-table-core, apply the changes from this PR to the fork and create a PR to the new repo. Thank you for the help

Sure, I'll have a go right away.

**Comment by hbermani** [comment]
So I had to amend the code slightly as the library moved to functional components. Updated the demo files and tested it. 

Credit goes to  @mogilvie  for original code. 

This is my first PR to an open source project so I hope it came through correctly 
Link to PR https://github.com/material-table-core/core/pull/86

**Comment by hbermani** [comment]
Right folks, the good news is we have working code, the less than good news is, we have a difference in opinion in how it should be implemented on the library. 

The new library already implements a solution where the data manipulation for complex object is handled at the exporter level, the proposed option adds additional flexibility to alter the data structure at the Column definition level before it's passed to the exporter ,much like how a render prop works or how you assign title, field etc. 

The former approach would mean you need to duplicate the data manipulation logic for each column across each custom exporter (be it csv, pdf, txt etc.) but is certainly flexible. On the other hand, in addition to having the ability to do that, you can with the proposed change just manipulate the data at the Column Definition level  to flatten it and that will ensure consistency and lack of duplications across exporters.

I could see benefits for both, with the proposed change giving additional flexibility, albeit, at the cost of obscurity. 

We would welcome your  thoughts on the new PR thread here. https://github.com/material-table-core/core/pull/86

**Comment by hbermani** [comment]
@mogilvie  You can close this one now, the PR has now been merged into master in the new library https://github.com/material-table-core/core/pull/86

**Pull request closed without merging**
