### PR TITLE
change selection all to not select disabled rows (code404msg original author)

### PR DESCRIPTION
**Pull request by gsstar9028**
## Related Issue
#686 

## Description
Material table select all on top also selects rows with checkbox disabled

## Impacted Areas in Application
List general components of the application that this PR will affect:

* This bug affects a component that I am using

## Additional Notes
:)

### CODE REVIEW

**Comment by KannarFr** [comment]
Hi @mbrn can you review this? :)

**Comment by gsstar9028** [comment]
@mbrn need one approval from reviewers with write access to merge this in.

**Comment by KannarFr** [comment]
@mbrn poke

**Comment by rchvalbo** [comment]
@mbrn Please review

**Comment by vireshshah** [comment]
@mbrn Please review and merge the changes.

**Comment by mbrn** [comment]
I started the work on PRs. I hope that all PRs will be processed in a few weeks. Versions will be published weekly. 

 Thanks for understanding

**Comment by Domino987** [comment]
There seems to be a conflict, can this be resolved?

**Comment by gsstar9028** [comment]
resolved conflict

**Comment by yathomasi** [comment]
is this going to be merged and released anytime soon?

**Comment by mbrn** [comment]
> is this going to be merged and released anytime soon?

Now:)

**Comment by Domino987** [comment]
@mbrn was it intendet to change the demojs file?

**Comment by mbrn** [comment]
> @mbrn was it intendet to change the demojs file?

Sorry, i merged it by mistake. But it is not problem. We can revert it manually later.

**Comment by yathomasi** [comment]
@mbrn thank you and also to all contributers  for this multifunctional table

**Comment by yathomasi** [comment]
image
Looks like the issues is still there
or do I need to pass any other value ?

**Comment by ashindiano** [comment]
The problem still exists, the rowdata.tabledata doesn't reflect disabled values

**Comment by gsstar9028** [comment]
oh man

**Comment by gsstar9028** [comment]
@code404sg

**Comment by ashindiano** [comment]
Tested again, It works when you set the following in selectionProps

  rowData.tableData.disabled = condition;

Followed the demo code 

selectionProps: rowData => {
                      rowData.tableData.disabled = rowData.name === 'A1';

                      return {
                        disabled: rowData.name === 'A1'
                      }
                    }

**Comment by code404sg** [comment]
@yathomasi please refer to @ashindiano comments.
thanks

**Comment by yathomasi** [comment]
@ashindiano  @code404sg
it only works for currently visible rowData's in current pagination 
i.e the disabled on other page are still selected 
can you guys verify ?

**Comment by yathomasi** [comment]
Page 1
Screenshot from 2020-06-17 11:32:33
Page 2
Screenshot from 2020-06-17 11:32:50
Page 2
Screenshot from 2020-06-17 11:33:06
Page 2
Screenshot from 2020-06-17 11:33:19

**Comment by code404sg** [comment]
@yathomasi that is correct. because the data being pass is not the whole record but the current page record. Is there any event like onload?

i tried this one
<code>
onSelectionChange = { (rows) =>{
                    console.log(rows.length )
                      return rows.map(row => {
                        row.tableData.disabled = row.name === 'A1';
                        return row;
                      })
                  }}
</code>

but you need to check and uncheck all to work.

**Comment by code404sg** [comment]
data={this.state.data.map(row => {
    row.tableData = { disabled: row.name === 'A1'};
   return row;
})

try above workaround

**Comment by code404sg** [comment]
@yathomasi

**Comment by yathomasi** [comment]
let me check

**Comment by yathomasi** [comment]
@code404sg  thank you so much it works

**Comment by code404sg** [comment]
no prob

**Comment by yathomasi** [comment]
```js
data={this.state.data.map(row => {
row.tableData = { ...row.tableData,disabled: row.name === 'A1'};
return row;
})
```
One thing make sure to use spread operator as that crashes on other operations

**Comment by PierreMage** [comment]
Combining @ashindiano and @code404sg workarounds:

```javascript
data={this.state.data.map(rowData => {
  rowData.tableData = { disabled: rowData.name === 'A1' };
  return rowData;
})}
options={{
  selectionProps: rowData => ({ disabled: rowData.tableData.disabled })
}}
```

**Pull request merged**
