### PR TITLE
Update grouping component

### PR DESCRIPTION
**Pull request by Domino987**
## Description
This PR changes the Groupbar component to a [chip](https://material-ui.com/demos/chips/), which is visual more appealing and enables a delete action to remove the grouping.
image

## Impacted Areas in Application
* GroupBar
* Table

## Additional Notes
Please let me know what you think about it and I would be happy to see this for the next release!

### CODE REVIEW

**Comment by mbrn** [comment]
Hi @Domino987 ,

Sorry i can not merge this component. Because after data-manager merge it needs some changes. Can you take a look at it please. Or open an issue, i can do it asap.

**Comment by Domino987** [comment]
Can you check if that can be merged or if I have to pull everything anew and add the code again?

**Comment by mbrn** [comment]
I think that it could not be merged. Because i changed many things in material-table.js .

**Comment by Domino987** [comment]
But i merged your code into mine and it looks good?

**Comment by mbrn** [comment]
ok.  i will recheck it again.

**Comment by Domino987** [comment]
@mbrn, so what do you think?

**Comment by mbrn** [comment]
sorry @Domino987 . I forgot this. I will look at it asap.

**Comment by mbrn** [comment]
I merge this manually @Domino987 . It will be in next release. Thanks for contribution

**Pull request closed without merging**
