### PR TITLE
Do not show hidden columns in columnsButton

### PR DESCRIPTION
**Pull request by esjayrockz**
## Related Issue
#1878

## Description
Fix to not show columns in columnsButton list which are marked as `hidden: true`.
If the user wants to hide a column by explicitly marking it as `hidden: true` in the code, it does not make sense to allow their users to be able to add back those columns from the columnsButton button as show in the related issue above.

## Impacted Areas in Application

- Toolbar
- List of columns shown when clicking on columnsButton
- This will now not show those columns any more which are marked explicitly as `hidden: true`.

## Additional Notes
This is my first contribution to open source outside my organization. I would love to work on more features/bugs on this project. Any feedback would be helpful.

### CODE REVIEW

**Comment by esjayrockz** [comment]
I don't know why the prettier check is failing here, considering that the pre-commit hooks have passed locally.

**Comment by mbrn** [comment]
Please resolve conflicts

**Comment by esjayrockz** [comment]
@mbrn Resolved conflicts.

**Comment by martin-trajanovski** [comment]
I dont know why this is done at all. I was using this functionality but now it is broken with this merge. I expect hidden: true to be shown in the list of available columns to be able to show/hide them.

**Comment by esjayrockz** [comment]
@martin-trajanovski If you don't know why a code change is done at all, please go and check the related issue.

**Comment by JBrutus3** [comment]
@martin-trajanovski i had a similar issue to you. Its not documented but if you want a column that is initiially hidden to be show in the list of available columns you need to add an additional property on the column called **hiddenByColumnsButton** to true along with setting **hidden** to true as well

**Comment by martin-trajanovski** [comment]
> @martin-trajanovski i had a similar issue to you. Its not documented but if you want a column that is initiially hidden to be show in the list of available columns you need to add an additional property on the column called **hiddenByColumnsButton** to true along with setting **hidden** to true as well

@JBrutus3 thank you I will have that in my mind when upgrading to the higher version again.

**Comment by kwaiksa** [comment]
This merge broke origin functionality. I try to fix my table by add **hiddenByColumnsButton** but meet this issue [#2414 ](https://github.com/mbrn/material-table/issues/2414)

**Comment by Samuel-Rider-Leck** [comment]
In adding support for a new use case, this implementation broke a previous use case of "hidden but revealable column" entirely.

`hiddenByColumnsButton: true` gives the same behavior as `hiddenByColumnsButton: false`.
`hidden: true` completely hides the column, and stops it from displaying in the column button (the intent of the merge).
`hiddenByColumnsButton: true, hidden: true` hides the column while displaying it in the column button, but revealing the column causes an error. 

Spent a hour looking into it myself, but the hidden variable is used in so many places it's difficult to tell where the issue originates. I'll be sticking with 1.64.0 until this is resolved.

**Comment by appukuttan-shailesh** [comment]
I am facing the same problem. Hoping there is an easy workaround.

**Comment by appukuttan-shailesh** [comment]
Example of the error when trying to unhide a `hidden:true` column using the `columnsButton`:

image

**Comment by priyankak10** [comment]
if hidden columns can not be brought back, what is the point of showing it in columns list with **hiddenByColumnsButton: true** 
if its visible user will select it to be shown and eventually table breaks.

**Comment by appukuttan-shailesh** [comment]
@priyankak10 : might be worth considering shifting to a fork of this project that has resolved this issue:
https://github.com/material-table-core/core

**Comment by JMG-Suntria** [comment]
2022 now. No apparent fix. I'll also be downgrading to 1.64.0. This bug is pretty bad for those of us trying to build effective and helpful tools for stakeholders. Good luck and thank you for your hard work.

**Comment by xoselolo** [comment]
2023. I'm not sure if has been a fix on this issue. I haven't found it anywhere. I'm using version 2.0.3 and still broken.

**Pull request merged**
