### PR TITLE
Add option don't allow editing on row

### PR DESCRIPTION
**Pull request by truongtv22**
## Related Issue
Relate the Github issue with this PR using `#`

## Description
Simple words to describe the overall goals of the pull request's commits.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

## Additional Notes
This is optional, feel free to follow your hearth and write here :)

### CODE REVIEW

**Comment by mbrn** [comment]
@truongtv22 

Why did you add a disabled flag. is Readonly flag not enough?

**Comment by truongtv22** [comment]
I encountered a column that does not allow editing when adding a new line.

**Comment by mbrn** [comment]
I think to replace readonly with editable flag that has `always|onUpdate|onAdd|never' (default always). What do you think? This will be more understandable, otherwise it is frustrating.

**Comment by truongtv22** [comment]
Awesome :)

**Pull request closed without merging**
