### PR TITLE
Add count as root prop

### PR DESCRIPTION
**Pull request by plummer-flex**
## Related Issue
#174

## Description
Add count global prop; if present override to Pagination

## Impacted Areas in Application
List general components of the application that this PR will affect:

* src/material-table.js

### CODE REVIEW

**Comment by mbrn** [comment]
Hi @plummer-flex ,

Why do you need this? If you add this feature to server side pagination, i will add complete solution for server side pagination, filtering etc.

**Comment by plummer-flex** [comment]
Correct, this feature is needed for server-side pagination.

Currently, this is the only prop that can not be managed externally without overriding the `Pagination` component.  `onChangePage ` and `onChangeRowsPerPage` gets us most of the way there, but the pagination nav is still based on `renderData.length`.   Overriding that with an root prop is the simplest solution.

**Comment by plummer-flex** [comment]
@mbrn I'm actually not following you.  Is there another implementation, or prop, for server-side pagination, filtering, or sorting?

**Comment by mbrn** [comment]
I think you for other datatable implementations. I don't know other datatables' features.

**Comment by vijthang61** [comment]
As mentioned by @plummer-flex , I would need this as well, the moment I override to make the count dynamic, the other props set like pagesize, onChangePage everything has to be provided as input to the custom pagination component again.

**Comment by vijthang61** [comment]
components={{            
            Pagination: props => (             
              <TablePagination
                  rowsPerPageOptions={[5, 10, 25]}
                  colSpan={3}
                  count={rows.length}
                  rowsPerPage={rowsPerPage}
                  page={page}
                  SelectProps={{
                    native: true,
                  }}
                  onChangePage={this.handleChangePage}
                  onChangeRowsPerPage={this.handleChangeRowsPerPage}
                  ActionsComponent={TablePaginationActionsWrapped}
                />              
            ),
          }}
          onChangeRowsPerPage = {this.handleChangeRowsPerPage}
          onChangePage = {this.handleChangePage}

The last two lines become waste as I have to provide it as input to the custom pagination component again

**Comment by plummer-flex** [comment]
@vijthang61 here's how I worked around it.
  - track local state for page, pageSize, column, direction
  - add handler functions for onChangePage, onChangeRowsPerPage, onOrderChange
  - override pagination and table body components to inject local state and settings
```
render() {
    const {
      columns,
      handlePage,
      handleRowsPerPage,
      handleOrder,
      handleSelect,
      icons
    } = this;

    const { page, pageSize } = this.state;

    const { count, data } = this.props;

    return (
      <MUITable
        title=""
        columns={columns}
        components={{
          Pagination: ({ ...otherProps }) => (
            <Pagination {...otherProps} icons={icons} count={count || 0} />
          ),
          Body: ({ renderData, ...subProps }) => (
            <Body
              {...subProps}
              currentPage={page}
              renderData={data}
              options={{ ...subProps.options, paging: false }} // set paging:false to avoid array slice
            />
          )
        }}
        data={data}
        onChangePage={handlePage}
        onChangeRowsPerPage={handleRowsPerPage}
        options={{ page, pageSize }}
        onOrderChange={handleOrder}
        onSelectionChange={handleSelect}
      />
    );
  }
```

**Comment by balanka** [comment]
I am stile getting this error 
I am using material-table core Version  6.3.2

**Pull request closed without merging**
