### PR TITLE
MUI 5 compatibility

### PR DESCRIPTION
**Pull request by villuv**
## Description

Work for Material UI 5 compatibility as there are some things renamed.

## Impacted Areas in Application

List general components of the application that this PR will affect:

* Pagination
* Theming
* Dependencies

## Additional Notes

This PR can be kept open at this moment, as there probably will be more breaking changes in MUI 5 coming.

### CODE REVIEW

**Comment by bneigher** [comment]
https://github.com/mbrn/material-table/issues/2556

**Comment by villuv** [comment]
I will try to migrate this also to material-ui-pickers 4.0.0-alpha.12 as it will also be merged to MUI core soon.

**Comment by villuv** [comment]
As material-pickers'  `LocalizationProvider` (previously known as `MuiPickersUtilsProvider`) will very likely be moved to MUI core as general purpose locale configuration provider, I suggest removing extra `LocalizationProvider` wrapper and its configuration from here and respect provider set by enclosing application. In case users need to override localization of one particular table instance, they could always wrap that particular instance with specific `LocalizationProvider`

**Comment by villuv** [comment]
material-pickers is now migrated to `@material-ui/lab`

**Comment by villuv** [comment]
Hi, @mbrn 
I don't really understand if the failing check is caused by me or is it something wrong with the pipeline. 
- Thanks

**Comment by bneigher** [comment]
for those of us (an increasing population) of people who have upgraded to MUI 5 - this is a real pain in the butt! Can we get this merged?

**Comment by villuv** [comment]
> for those of us (an increasing population) of people who have upgraded to MUI 5 - this is a real pain in the butt! Can we get this merged?

According to README, @mbrn is probably not going to merge this before refactoring is done, even though I can't seem to find a branch where refactirubg work is going on, it's probably private for some reason. On the other hand MUI 5 is still currently very alpha and breaking changes are coming in every couple of weeks, so merging this into master is probably not a good idea anyway before it gets stabilized (say, beta)

As I am one of the people with a painful butt, I mainly keep this PR up for tracking my work and in case someone finds it useful too. If it is any use for material-table in general, is up to maintainer's to decide. That said, I'd be glad to hear some comments from them.

**Comment by bneigher** [comment]
but why not have a @next branch and push tags on that

**Comment by villuv** [comment]
> but why not have a @next branch and push tags on that

I don't know. This is up to maintainers to decide. I'm just another user trying to help...

**Review by superyhee — APPROVED** [review]

**Comment by dansoftwares24** [comment]
Thanks for the contribution. It saved the day!

**Comment by iamchathu** [comment]
Any update on this?

**Comment by villuv** [comment]
> Any update on this?

It has been quiet here. But basically the same PR got merged to 'next' branch of this: https://github.com/material-table-core/core/tree/next which is a community fork of this repo and it has more active development. At least I'm in process of migrating our projects to that fork.

**Pull request closed without merging**
