### PR TITLE
Add autocomplete to edit field

### PR DESCRIPTION
**Pull request by matt-eric**
## Related Issue

#1410 

## Description

Enables `Autocomplete` inputs to be used as edit fields.

image

## Impacted Areas in Application

m-table-edit-field.js

## Additional Notes

An example of how the `Autocomplete` is added to the `columns` prop in the `<MaterialTable/>` component is here:

image

The `autocomplete` key is given an array to be used as the `options` for the `Autocomplete` input element. The `autocompleteFreeSolo` prop can optionally be configured here as well.

The `fontSize` for the other editable input components has been adjusted to the default `fontSize` (from 13 to 16) because there were issues with adjusting the `fontSize` of the `Autocomplete`. The `fontSize` for table cells in the non-editable state remains the same.

Please let me know if you have any comments or questions. I'm able to make additional changes if requested.

### CODE REVIEW

**Comment by matt-eric** [comment]
I made all the requested changes from https://github.com/mbrn/material-table/pull/1999.

**Comment by mbrn** [comment]
Hi @matt-eric 

Thanks for your effort. But i can't merge this pr. It contains a lot of changes. We will start to a big refactor, testing progress. So i won't accept big changes on code. We will implement this feature later. Thanks for your understanding.

**Comment by matt-eric** [comment]
@mbrn - Sounds good. We are using this feature in production and look forward to it being implemented at some point. Thanks.

**Comment by vedpbharti** [comment]
Hi Team when will this be available?

**Pull request closed without merging**
