### PR TITLE
Update Issue Templates

### PR DESCRIPTION
**Pull request by oze4**
Resolve issue #1707 

## Related Issue
#1707 

## Description
When using selection with grouping, `this.props.level` appears to be undefined. `this.props.level` is used in calculations to determine some CSS properties, ultimately resulting in `NaN` and an error after expanding grouped column.

## Related PRs
NA

## Impacted Areas in Application
List general components of the application that this PR will affect:

* m-table-body-row.js

## Additional Notes
NA

### CODE REVIEW

**Comment by jroyleaz** [comment]
Any movement on this? It seems like a small but worthwhile bug fix.

**Comment by oze4** [comment]
@jroyleaz I wouldn't count on this PR getting merged. This repo seems pretty much dead.

**Comment by jroyleaz** [comment]
@oze4 Hmm, thanks for the heads up. I think I'll just fork it and do it myself, then. I'd like to expose more of the internals so you can change sorting, grouping, etc from actions. And maybe cross link search between MT instances with a shared context. 👍

**Comment by oze4** [comment]
@jroyleaz a local fork is prob the best route to be honest. They're *extremely* slow moving in this repo and not very responsive. It's sad because this repo produces a solid product.. It's even more unfortunate since this repo is referenced in the official Material UI docs as a table "you should check out".

**Comment by jroyleaz** [comment]
@oze4 yeah, for sure. It's a great product that has been hugely helpful in my current project. I also found it through the material UI docs. 👍

**Comment by oze4** [comment]
@jroyleaz I started a maintained for [here](https://github.com/oze4/material-table-core). You can also [find more here](https://material-table-core.com)! This change has been made in that repo.

**Comment by oze4** [comment]
@mbrn I updated the Issue Templates in this PR - can you review?

**Pull request merged**
