### PR TITLE
Group key null check

### PR DESCRIPTION
**Pull request by Foosballfan**
## Description
When a value equals 0, the existing logic for the key of a Group Row can cause key errors and thus repeated rows.
This change does not count 0 as a null value.

## Impacted Areas in Application
List general components of the application that this PR will affect:

*Grouping

Screenshot 2019-05-13 at 12 29 18

### CODE REVIEW

**Comment by mbrn** [comment]
No difference

**Comment by Foosballfan** [comment]
@mbrn can you please elaborate? I went to a lot of effort describing the change and your 2 word response is very unclear.

**Comment by mbrn** [comment]
Hi @Foosballfan,

Thanks for your effort. But i asked a question(What is the difference?).

**Comment by Foosballfan** [comment]
The difference is that 0 was being treated as a null value, when it is in fact a valid value.

The change I made is to only treat null or undefined as null values.

In the screen shot I show how treating 0 as a null value causes the rows to be duplicated as a result of React duplicate key errors.

> When a value equals 0, the existing logic for the key of a Group Row can cause key errors and thus repeated rows.
>This change does not count 0 as a null value.

**Comment by mbrn** [comment]
This is the answer. Thanks.

**Pull request merged**
