### PR TITLE
Added searchText to options.

### PR DESCRIPTION
**Pull request by naum-d**
Added searchText option to initialize search field before table was render.

### CODE REVIEW

**Comment by tobilarscheid** [comment]
Hi @naum-d, this looks similar to what I did here: https://github.com/mbrn/material-table/pull/1137

(actually, your solution feels simpler!)

**Comment by mbrn** [comment]
This is same with #1137, but it looks simpler. So i will merge this and close #1137.

Thanks for contribution @naum-d ,

You too @tobilarscheid

**Comment by tobilarscheid** [comment]
@mbrn when will this be released?

**Comment by mbrn** [comment]
I hope tomorrow. We need to test version before publish it.

**Comment by naum-d** [comment]
@mbrn Hello.) When can you update npm library?)

**Comment by ingvaldlorentzen** [comment]
Any update on new version with this feature?

**Comment by krnareshkumar23** [comment]
I couldn't see an option to set initial searchText in v1.54.2 yet. or am I missing something.
if not available yet could you let know when it will be available?

**Comment by ingvaldlorentzen** [comment]
Just add the `searchText` key to the `options` prop. 

```
<MaterialTable columns={columns}
                   data={data}
                   options={{searchText: 'Something to search for'}}
                   title='Cool Table'/>
```

Works well for me on `1.54.2`, seems like it's missing in the [documentation](https://material-table.com/#/docs/all-props) though.

**Comment by thedmeyer** [comment]
Is this working?

**Comment by tobilarscheid** [comment]
I am using v 1.54 and it works!

**Pull request merged**
