### PR TITLE
Approve edit/add on enter added

### PR DESCRIPTION
**Pull request by vijaypushkin**
## Related Issue
#1364 
#1162 

## Description
This PR will add the feature to save edit/add upon pressing enter key

## Related PRs
#1691 

## Impacted Areas in Application
List general components of the application that this PR will affect:

* Edit Row
* Add Row

### CODE REVIEW

**Comment by mbrn** [comment]
Please resolve conflicts

**Comment by vijaypushkin** [comment]
@mbrn, Resolved conflicts

**Comment by Vitaliytheone** [comment]
Hi. Why don't work in 1.65? Need a prop?

**Comment by gxtaillon** [comment]
@vijaypushkin @mbrn This PR seems to break textarea/multiline editing (#934, #1023). Whenever enter is pressed to put a line feed in, it submits the row.

Checking for text area may be a quick fix here : https://github.com/mbrn/material-table/pull/2008/files#diff-2cdb9894645bebfaeabad3bf15c5a5f8R238

```js
if (e.keyCode === 13) {
    if (e.target.nodeName != 'TEXTAREA' && e.target.type != 'textarea') {
        //....
    }
}
```

But it would be great to have an option to toggle the whole feature as well too.

Right now there's a workaround but it involves copy-pasting the real code but without the handleSave.

```js
components={{
    EditRow: (props) => <MTableEditRow {...props} onKeyDown={(e) => {
        if (e.keyCode === 27) {
            props.onEditingCanceled(props.mode, props.data)
        }
    }} />
}} 
```

Best

**Comment by vijaypushkin** [comment]
Hi @vuongductuanktmt and @gxtaillon I have fixed with this PR #2227

For text-area a.k.a Material UI TextField multiline
* Enter key will work as expected, goes to new line
* Shift + Enter will save the row when it's on edit / add mode on text-area

**Comment by nilay-pirhoalpha** [comment]
Hey Guys! I was trying to use this library with the **validation** feature. I'm facing an issue. 
The `edit/add on Enter press` _does not confirm the validations and directly saves the changes_. **Even if validations are showing an error.** 

I'm handling it the way @gxtaillon suggested for text area https://github.com/mbrn/material-table/pull/2008#issuecomment-662529834 to disable the enter button submit altogether. But I think it can be handled better? Or Maybe restrict the save to trigger on `shift+enter` only instead of `enter` and `shift+enter` ?
https://github.com/mbrn/material-table/blob/429edb1b4f65345a17b71ed61b6004fb1e42e4da/src/components/m-table-edit-row.js#L236-L244

**Comment by nilaysavant** [comment]
Hey Guys! I was trying to use this library with the **validation** feature. I'm facing an issue. The `edit/add on Enter press` _does not confirm the validations and directly saves the changes_. **Even if validations are showing an error.** 

I'm handling it the way @gxtaillon suggested for text area https://github.com/mbrn/material-table/pull/2008#issuecomment-662529834 to disable the enter button submit altogether. But I think it can be handled better? Or Maybe restrict the save to trigger on `shift+enter` only instead of `enter` and `shift+enter` ? https://github.com/mbrn/material-table/blob/429edb1b4f65345a17b71ed61b6004fb1e42e4da/src/components/m-table-edit-row.js#L236-L244

**Comment by imnasnainaec** [comment]
> @vijaypushkin @mbrn This PR seems to break textarea/multiline editing (#934, #1023). Whenever enter is pressed to put a line feed in, it submits the row.
> 
> Checking for text area may be a quick fix here : https://github.com/mbrn/material-table/pull/2008/files#diff-2cdb9894645bebfaeabad3bf15c5a5f8R238
> 
> ```js
> if (e.keyCode === 13) {
>     if (e.target.nodeName !== 'TEXTAREA' && e.target.type !== 'textarea') {
>         //....
>     }
> }
> ```
> 
> But it would be great to have an option to toggle the whole feature as well too.
> 
> Right now there's a workaround but it involves copy-pasting the real code but without the handleSave.
> 
> ```js
> components={{
>     EditRow: (props) => <MTableEditRow {...props} onKeyDown={(e) => {
>         if (e.keyCode === 27) {
>             props.onEditingCanceled(props.mode, props.data)
>         }
>     }} />
> }} 
> ```
> 
> Best

@gxtaillon Is there a way to bypass the enter behavior for just one column?

**Comment by gxtaillon** [comment]
@imnasnainaec The attribute ariaLabel seems to be populated with the column title (e.target.ariaLabel) but I would not recommend relying on that since I would not expect this to be considered part of the interface and may change for any reason between version upgrades. You might want to submit a feature request to populate the target with the column field and make sure it become a supported way of interacting with the table.

**Pull request merged**
