### PR TITLE
Bug/export to csv custom field fix

### LINKED ISSUE #543: Some fields are not exported in the CSV
**Describe the bug**
Fields are missing in the exported CSV. 

I've just noticed that fields with custom value are not exported in the CSV. See code below that concatenates the year and month.

```
                columns={[
                  {
                    title: 'Date', headerStyle: {minWidth: '20px', maxWidth: '20px'},
                  cellStyle: data => { return { paddingRight: 4, paddingLeft: 5,minWidth: '20px', maxWidth: '20px' }},   
                    render: rowData => rowData.year + '-' + rowData.month + '-' + rowData.day
                  },
                  {
                    title: 'P/L%', headerStyle: {paddingRight: 4, paddingLeft: 5,minWidth: '35px', maxWidth: '35px'},
                    cellStyle: data => { return { paddingRight: 4, paddingLeft: 5,minWidth: '35px', maxWidth: '35px' }}, 
                    field: 'profit_percent', type: 'numeric',         
                    render: rowData => {
                      var profit_percent = parseFloat(rowData.profit)/parseFloat(rowData.investment) * 100
                      var profit = parseFloat(profit_percent).toFixed(2) + '%'
                      var bgcolor;
                      var fontColor = 'black';
                      if (profit_percent < 0) {
                        bgcolor = '#b71c1c';
                        fontColor = 'white';
                      }
                      else if (profit_percent > 0) {
                        bgcolor = '#4caf50';
                        fontColor = 'white';
                      }
                      return (
                        <div
                          style={{
                            float: 'right',
                            padding: 1,
                            color: fontColor,
                            maxWidth: 50,
                            backgroundColor: bgcolor,
                            height: 20,
                          }}
                        >
                          {profit}
                        </div>
                      )
                    }
                  },
                  {
                    title: 'P/L', field: 'revenue', type: 'numeric', headerStyle: {paddingRight: 4, paddingLeft: 5,minWidth: '100px', maxWidth: '100px' },
                    cellStyle: data => { return { paddingRight: 4, paddingLeft: 5,minWidth: '100px', maxWidth: '100px'  } },
                    render: rowData => rowData.profit.toFixed(8)
                  },
                  {
                    title: 'Investment', type: 'numeric', headerStyle: {paddingRight: 4, paddingLeft: 5, minWidth: '100px', maxWidth: '100px' },
                    cellStyle: data => { return {paddingRight: 4, paddingLeft: 5,minWidth: '100px', maxWidth: '100px'} },
                    render: rowData => parseFloat(rowData.investment).toFixed(8)
                  },
                  {
                    title: 'Revenue', field: 'revenue', type: 'numeric',  headerStyle: {paddingRight: 4, paddingLeft: 5, minWidth: '100px', maxWidth: '100px' },
                    cellStyle: data => { return {paddingRight: 4, paddingLeft: 5,minWidth: '100px', maxWidth: '100px'} },
                    render: rowData => parseFloat(rowData.revenue).toFixed(8)
                  },
                  {
                    title: 'Commission', field: 'base_commission', type: 'numeric',  headerStyle: {paddingRight: 4, paddingLeft: 5, minWidth: '100px', maxWidth: '100px' },
                    cellStyle: data => { return {paddingRight: 4, paddingLeft: 5,minWidth: '100px', maxWidth: '100px'} },
                    render: rowData => parseFloat(rowData.base_commission).toFixed(8)
                  },                  
                  {
                    title: 'Cummulative Profit', field: 'cummulative_profit', type: 'numeric', headerStyle: {paddingRight: 4, paddingLeft: 5,minWidth: '100px', maxWidth: '100px'},
                    cellStyle: data => { return {paddingRight: 4, paddingLeft: 5,minWidth: '100px', maxWidth: '100px'} },
                    render: rowData => parseFloat(rowData.cummulative_profit).toFixed(8)
                  },
                  {
                    title: 'Won', field: 'won', type: 'numeric', headerStyle: { maxWidth: '20px' },
                    cellStyle: data => { return { maxWidth: '20px' } },
                  },
                  {
                    title: 'Lost', field: 'lost', type: 'numeric', headerStyle: { maxWidth: '20px' },
                    cellStyle: data => { return { maxWidth: '20px' } },
                  },
                  {
                    title: 'Avg Holding Time', headerStyle: { paddingRight: 4, paddingLeft: 5,minWidth: '80px'},
                    cellStyle: data => { return {paddingRight: 4, paddingLeft: 5,minWidth: '80px'} },
                    render: rowData => formatDistance(Date.now(),Date.now() - rowData.total_hold_time/rowData.tran_count),
                  }
```

**To Reproduce**
1. In the table, click the Export to CSV.

**Expected behavior**
The CSV should contain the custom field.

**Screenshots**
Table
image

CSV
It is missing the Date, P/L% (no value), Investment, Average Holding Time.
[Daily Sales.xlsx](https://github.com/mbrn/material-table/files/3144855/Daily.Sales.xlsx)

### PR DESCRIPTION
**Pull request by theamanbhargava**
## Related Issue
Fixes #543 

## Description
Custom columns using a render method without field were not being output in the CSV file because typechecking was filtering out columns without a `field` attribute.
A dataAccessor prop was added to column which is a function that would return the value that is going to be printed to the export file. So now for render methods with JSX return values, dataAccessor prop is used instead to getFieldValue.

## Impacted Areas in Application
`getFieldValue()` method was changed to adapt to requirements.
Demo page was changed to accommodate example of a custom field with render method without field field attribute. 
dataAccessor prop was added to prop-types.js

## Additional Notes
Thanks to https://github.com/mbrn/material-table/issues/543#issuecomment-490833307 for pointers to the solution.

### CODE REVIEW

**Comment by mbrn** [comment]
This would be a good solution, but i want to think about this.

**Comment by theamanbhargava** [comment]
@mbrn sure, take your time please, a lot of other libraries such as react-big-calendar make excessive use of dataAccessors to make sure values are displayed as expected and it works fantastically.

**Comment by mbrn** [comment]
Instead of using a dataAccessor we can do this:

1. Do not touch datamanager. 
2. index.d.ts:      export: boolean | ((rowData:any) => string); 
3. Just use export field as function
    - export == false => do not export
    - export is function => use export(rowData)
    - export == true but field is undefined => do not export
    - export == true and field has value => export field value

What do you think about this.

**Comment by mbrn** [comment]
I will add same functionality with another way. Thanks for your effort.

**Pull request closed without merging**
