### PR TITLE
Draggable rows / rows reordering / drag & drop rows

### PR DESCRIPTION
**Pull request by dekelb**
## Related Issue
This PR relates to #1219

## Description
This PR implements the draggable rows feature. It has both full-row drag and drop, and left-most table cell with "=" icon to support drag and drop using only 1 column.
Also - the content of the cell can support other components, so it's also possible to have an "draggable" icon for that.

The "demo.js" has the implementation of both features.

### CODE REVIEW

**Comment by LeanderCoevoet** [comment]
First of all, love the PR. I was also working on this issue so I have some suggestions for this PR:

- There are still some warning from react-beautiful-dnd those need to be fixed.
- Add the extra options to the index.d.ts file so the options are available in typescript.
- Add the extra options draggableRowsOptions object in full in the prop-types file.

**Comment by dekelb** [comment]
@LeanderCoevoet thanks for your PR to my code, I merged it.

I'll also make some changes based on your comments. If someone else has more comments/requests please feel free to add them.

I think this feature is really important and hopefully it will be merged soon and another version of the lib will be released.

**Comment by dekelb** [comment]
@LeanderCoevoet I merged the changes you requested. Will appreciate another review.

Also - you mentioned that you also started to work on this feature - do you think I missed something?
Here is what was important for me to cover:
1. Make sure columns drag&drop is still working (both reordering and grouping)
2. Support full-row drag
3. Support drag by cell (instead of full row)
4. Make sure there is no collision when there is a filtering row and a select column

**Comment by LeanderCoevoet** [comment]
@dekelb

A feature you may have missed is to drag and drop multiple rows.
This feature off course can be added later.
I personally miss the feature to be able to drag and drop a row from 1 table to another table.
Here for you need to disable the dragdropContext and wrap 2 tables in a DragDropContext with a custom onDragEnd method. I was doing this on my branch but it got a bit messy so I will take your changes and work further on them.
So I think you didn't miss anything important for this feature.

**Comment by dekelb** [comment]
@LeanderCoevoet thanks!
I didn't work on the multiple rows nor on the drag & drop between two tables, mostly because I didn't need those features, but as you mentioned - this is something that we can add later on (after this PR is merged).

@mbrn waiting for your review on this one. Thanks!

**Comment by kgstew** [comment]
This would be a excellent feature to get added. We attempted to integrate `react-beautiful-dnd` but ran into trouble with being able to add the Draggable wrapper around the TableRow. This looks like it solves all those problems. Thank you @dekelb for doing this!

**Comment by dekelb** [comment]
@kgstew thanks for your feedback! It took some time to make sure everything work as expected (and there were a few edge cases there...).

I really hope the core team will give feedback and will allow merging this feature into the lib @mbrn @Domino987 @oze4.
I know there are also two other PR's based on this feature, and based on the original issue (#1219) there are many people who are waiting for it.

**Comment by Domino987** [comment]
Hi everybody, I really like what you did here and it's greatly appreciated. I think this will be a great addition, and I will take a look at the implementation itself. We would also need to update the docs (separate repo), to reflect these changes and show a example implementations. We are currently working in reducing the issues and PRs so I think this will play nicely with that. I will to a review tomorrow. Great job and thank you again.

**Comment by dekelb** [comment]
> Hi everybody, I really like what you did here and it's greatly appreciated. I think this will be a great addition, and I will take a look at the implementation itself. We would also need to update the docs (separate repo), to reflect these changes and show a example implementations. We are currently working in reducing the issues and PRs so I think this will play nicely with that. I will to a review tomorrow. Great job and thank you again.

Thanks for your reply @Domino987! much appreciated.
Regarding the docs - I agree, I didn't see any docs inside the repo (is there another repo for that? I'm happy to contribute there as well).
Regarding the demo - I updated the default demo to include the drag&drop options, so it's easy to understand how it works/looks. If something is missing there please let me know.

**Comment by mbrn** [comment]
Hi @dekelb 

Thanks for your great effort. It is really useful feature. Actually i must merge this branch now. Because i am merging prs by sort of creation date. But i will skip this pr for this week. Because it contains a lot of changes. And i will compare other solution based on the same issue. 

I hope that this will be merged at next week. Thanks for your understanding.

**Comment by dekelb** [comment]
@mbrn sure, no problem.
If there is something I can do to help push this faster please let me know.

**Comment by mbrn** [comment]
Please resolve conflicts

**Comment by dekelb** [comment]
@mbrn conflicts resolved.
I see that the prettier workflow failed, not sure why - locally prettier run and everything is fixed there (I don't have permission to re-run the workflow).

**Comment by Leocete** [comment]
@dekelb, I can see from your commit that your Prettier changed the code style. I think that to pass the check you need to either turn off your local prettier or configure it as it is configured for Material-Table project.

**Comment by dekelb** [comment]
@Leocete thanks for your reply.
The error on the prettier cli is `##[error]The process '/usr/bin/git' failed with exit code 1`, so I'm pretty sure it's not really a prettier issue.
There are also other PRs that failed exactly on this.
Waiting for @mbrn to check it.

**Comment by PATTANPARVIN** [comment]
Please fix this feature as we are waiting for this.

**Comment by Leocete** [comment]
@dekelb, btw I've tried your pull request on my project - thank you very much for your work, drag'n'drop works perfectly.
However, after I pulled your changes I faced a strange bug - `rowStyle` can't be applied to my table, previously it was working:
```
rowStyle: (rowData) => ({
      backgroundColor: selectedRow === rowData.tableData.id ? '#EEE' : '#FFF',
      fontSize: '12px',
      hover: {
        backgroundColor: '#EEE',
      },
    })
```

Can you check if you can update your row style with `rowStyle` attribute?

**Comment by dekelb** [comment]
@Leocete really good catch!
The rowStyle Issue is now fixed :-) (also doubled check the eslint/prettier things and made sure all tests pass).

(The issue with the Prettier CLI job is not related to the code).

**Comment by Leocete** [comment]
@dekelb, thank you! 
Maybe I'm doing something wrong, but I've tried to add rowStyle to your `demo.js` table, like that:
```
options={{
                filtering: true,
                grouping: true,
                groupTitle: (group) => group.data.length,
                searchFieldVariant: "outlined",
                draggable: this.state.dragOption === "columns",
                rowStyle: (rowData) => {
                  backgroundColor: 'red'
                },
                draggableRows:
                  this.state.dragOption === "cell" ||
                  this.state.dragOption === "row",
                draggableRowsOptions: {
                  draggableCell: this.state.dragOption === "cell",
                  dragCellContent: "=",
                  dragCellWidth: "40px",
                },
              }}
```

but it didn't change the row color
can you take a look at it please?

**Comment by Leocete** [comment]
@dekelb, I've fixed that bug with moveing `providedStyles` to the `getStyles` method, can you update your pull request please? 

Here is the updated component:
```
/* eslint-disable no-unused-vars */
import Checkbox from "@material-ui/core/Checkbox";
import TableCell from "@material-ui/core/TableCell";
import TableRow from "@material-ui/core/TableRow";
import IconButton from "@material-ui/core/IconButton";
import Icon from "@material-ui/core/Icon";
import Tooltip from "@material-ui/core/Tooltip";
import PropTypes from "prop-types";
import * as React from "react";
import * as CommonValues from "../utils/common-values";
import { DragDropContext, Droppable, Draggable } from "react-beautiful-dnd";
/* eslint-enable no-unused-vars */

export default class MTableBodyRow extends React.Component {
  renderColumns() {
    const size = CommonValues.elementSize(this.props);
    const mapArr = this.props.columns
      .filter(
        (columnDef) =>
          !columnDef.hidden && !(columnDef.tableData.groupOrder > -1)
      )
      .sort((a, b) => a.tableData.columnOrder - b.tableData.columnOrder)
      .map((columnDef, index) => {
        const value = this.props.getFieldValue(this.props.data, columnDef);
        return (
          <this.props.components.Cell
            size={size}
            errorState={this.props.errorState}
            icons={this.props.icons}
            columnDef={{
              cellStyle: this.props.options.cellStyle,
              ...columnDef,
            }}
            value={value}
            key={
              "cell-" +
              this.props.data.tableData.id +
              "-" +
              columnDef.tableData.id
            }
            rowData={this.props.data}
          />
        );
      });
    return mapArr;
  }

  renderActions() {
    const size = CommonValues.elementSize(this.props);
    const actions = CommonValues.rowActions(this.props);
    const width = actions.length * CommonValues.baseIconSize(this.props);
    return (
      <TableCell
        size={size}
        padding="none"
        key="key-actions-column"
        style={{
          width: width,
          padding: "0px 5px",
          boxSizing: "border-box",
          ...this.props.options.actionsCellStyle,
        }}
      >
        <div style={{ display: "flex" }}>
          <this.props.components.Actions
            data={this.props.data}
            actions={actions}
            components={this.props.components}
            size={size}
            disabled={this.props.hasAnyEditingRow}
          />
        </div>
      </TableCell>
    );
  }

  renderSelectionColumn() {
    let checkboxProps = this.props.options.selectionProps || {};
    if (typeof checkboxProps === "function") {
      checkboxProps = checkboxProps(this.props.data);
    }

    const size = CommonValues.elementSize(this.props);
    const selectionWidth = CommonValues.selectionMaxWidth(
      this.props,
      this.props.treeDataMaxLevel
    );

    const styles =
      size === "medium"
        ? {
            marginLeft: this.props.level * 9,
          }
        : {
            padding: "4px",
            marginLeft: 5 + this.props.level * 9,
          };

    return (
      <TableCell
        size={size}
        padding="none"
        key="key-selection-column"
        style={{ width: selectionWidth }}
      >
        <Checkbox
          size={size}
          checked={this.props.data.tableData.checked === true}
          onClick={(e) => e.stopPropagation()}
          value={this.props.data.tableData.id.toString()}
          onChange={(event) =>
            this.props.onRowSelected(event, this.props.path, this.props.data)
          }
          style={styles}
          {...checkboxProps}
        />
      </TableCell>
    );
  }

  renderDraggableColumn() {
    const draggableOptions = this.props.options.draggableRowsOptions;
    return (
      <TableCell
        padding="none"
        key="key-drag-column"
        style={{ width: draggableOptions.dragCellWidth }}
      />
    );
  }

  rotateIconStyle = (isOpen) => ({
    transform: isOpen ? "rotate(90deg)" : "none",
  });

  renderDetailPanelColumn() {
    const size = CommonValues.elementSize(this.props);
    const CustomIcon = ({ icon, iconProps }) =>
      typeof icon === "string" ? (
        <Icon {...iconProps}>{icon}</Icon>
      ) : (
        React.createElement(icon, { ...iconProps })
      );

    if (typeof this.props.detailPanel == "function") {
      return (
        <TableCell
          size={size}
          padding="none"
          key="key-detail-panel-column"
          style={{
            width: 42,
            textAlign: "center",
            ...this.props.options.detailPanelColumnStyle,
          }}
        >
          <IconButton
            size={size}
            style={{
              transition: "all ease 200ms",
              ...this.rotateIconStyle(
                this.props.data.tableData.showDetailPanel
              ),
            }}
            onClick={(event) => {
              this.props.onToggleDetailPanel(
                this.props.path,
                this.props.detailPanel
              );
              event.stopPropagation();
            }}
          >
            <this.props.icons.DetailPanel />
          </IconButton>
        </TableCell>
      );
    } else {
      return (
        <TableCell size={size} padding="none" key="key-detail-panel-column">
          <div
            style={{
              width: 42 * this.props.detailPanel.length,
              textAlign: "center",
              display: "flex",
              ...this.props.options.detailPanelColumnStyle,
            }}
          >
            {this.props.detailPanel.map((panel, index) => {
              if (typeof panel === "function") {
                panel = panel(this.props.data);
              }

              const isOpen =
                (this.props.data.tableData.showDetailPanel || "").toString() ===
                panel.render.toString();

              let iconButton = <this.props.icons.DetailPanel />;
              let animation = true;
              if (isOpen) {
                if (panel.openIcon) {
                  iconButton = (
                    <CustomIcon
                      icon={panel.openIcon}
                      iconProps={panel.iconProps}
                    />
                  );
                  animation = false;
                } else if (panel.icon) {
                  iconButton = (
                    <CustomIcon icon={panel.icon} iconProps={panel.iconProps} />
                  );
                }
              } else if (panel.icon) {
                iconButton = (
                  <CustomIcon icon={panel.icon} iconProps={panel.iconProps} />
                );
                animation = false;
              }

              iconButton = (
                <IconButton
                  size={size}
                  key={"key-detail-panel-" + index}
                  style={{
                    transition: "all ease 200ms",
                    ...this.rotateIconStyle(animation && isOpen),
                  }}
                  disabled={panel.disabled}
                  onClick={(event) => {
                    this.props.onToggleDetailPanel(
                      this.props.path,
                      panel.render
                    );
                    event.stopPropagation();
                  }}
                >
                  {iconButton}
                </IconButton>
              );

              if (panel.tooltip) {
                iconButton = (
                  <Tooltip
                    key={"key-detail-panel-" + index}
                    title={panel.tooltip}
                  >
                    {iconButton}
                  </Tooltip>
                );
              }

              return iconButton;
            })}
          </div>
        </TableCell>
      );
    }
  }

  renderTreeDataColumn() {
    const size = CommonValues.elementSize(this.props);
    if (
      this.props.data.tableData.childRows &&
      this.props.data.tableData.childRows.length > 0
    ) {
      return (
        <TableCell
          size={size}
          padding="none"
          key={"key-tree-data-column"}
          style={{ width: 48 + 9 * (this.props.treeDataMaxLevel - 2) }}
        >
          <IconButton
            size={size}
            style={{
              transition: "all ease 200ms",
              marginLeft: this.props.level * 9,
              ...this.rotateIconStyle(this.props.data.tableData.isTreeExpanded),
            }}
            onClick={(event) => {
              this.props.onTreeExpandChanged(this.props.path, this.props.data);
              event.stopPropagation();
            }}
          >
            <this.props.icons.DetailPanel />
          </IconButton>
        </TableCell>
      );
    } else {
      return <TableCell padding="none" key={"key-tree-data-column"} />;
    }
  }

  getStyle(index, level, providedStyle) {
    let style = {
      transition: "all ease 300ms",
    };

    if (typeof this.props.options.rowStyle === "function") {
      style = {
        ...style,
        ...this.props.options.rowStyle(this.props.data, index, level),
        ...providedStyle
      };
    } else if (this.props.options.rowStyle) {
      style = {
        ...style,
        ...this.props.options.rowStyle,
        ...providedStyle
      };
    }

    if (this.props.onRowClick) {
      style.cursor = "pointer";
    }

    if (this.props.hasAnyEditingRow) {
      style.opacity = 0.2;
    }

    return style;
  }

  render() {
    const size = CommonValues.elementSize(this.props);
    const renderColumns = this.renderColumns();
    if (this.props.options.selection) {
      renderColumns.splice(0, 0, this.renderSelectionColumn());
    }
    if (
      this.props.actions &&
      this.props.actions.filter(
        (a) => a.position === "row" || typeof a === "function"
      ).length > 0
    ) {
      if (this.props.options.actionsColumnIndex === -1) {
        renderColumns.push(this.renderActions());
      } else if (this.props.options.actionsColumnIndex >= 0) {
        let endPos = 0;
        if (this.props.options.selection) {
          endPos = 1;
        }
        renderColumns.splice(
          this.props.options.actionsColumnIndex + endPos,
          0,
          this.renderActions()
        );
      }
    }

    // Then we add detail panel icon
    if (this.props.detailPanel) {
      if (this.props.options.detailPanelColumnAlignment === "right") {
        renderColumns.push(this.renderDetailPanelColumn());
      } else {
        renderColumns.splice(0, 0, this.renderDetailPanelColumn());
      }
    }

    // Lastly we add tree data icon
    if (this.props.isTreeData) {
      renderColumns.splice(0, 0, this.renderTreeDataColumn());
    }

    this.props.columns
      .filter((columnDef) => columnDef.tableData.groupOrder > -1)
      .forEach((columnDef) => {
        renderColumns.splice(
          0,
          0,
          <TableCell
            size={size}
            padding="none"
            key={"key-group-cell" + columnDef.tableData.id}
          />
        );
      });

    const {
      icons,
      data,
      columns,
      components,
      detailPanel,
      getFieldValue,
      isTreeData,
      onRowClick,
      onRowSelected,
      onTreeExpandChanged,
      onToggleDetailPanel,
      onEditingCanceled,
      onEditingApproved,
      options,
      hasAnyEditingRow,
      treeDataMaxLevel,
      localization,
      actions,
      errorState,
      ...rowProps
    } = this.props;

    return (
      <>
        <Draggable
          isDragDisabled={!options.draggableRows}
          key={"row-" + this.props.index.toString()}
          draggableId={"row-" + this.props.index.toString()}
          index={this.props.index}
        >
          {(provided, snapshot) => {
            const {
              style: providedStyle,
              ...providedDraggableProps
            } = provided.draggableProps;
            const rowStyle = {
              ...this.getStyle(this.props.index, this.props.level),
              ...providedStyle,
            };
            return (
              <TableRow
                selected={hasAnyEditingRow}
                {...rowProps}
                hover={onRowClick ? true : false}
                style={this.getStyle(this.props.index, this.props.level, providedStyle)}
                onClick={(event) => {
                  onRowClick &&
                    onRowClick(event, this.props.data, (panelIndex) => {
                      let panel = detailPanel;
                      if (Array.isArray(panel)) {
                        panel = panel[panelIndex || 0];
                        if (typeof panel === "function") {
                          panel = panel(this.props.data);
                        }
                        panel = panel.render;
                      }

                      onToggleDetailPanel(this.props.path, panel);
                    });
                }}
                ref={provided.innerRef}
                {...providedDraggableProps}
                {...(options.draggableRowsOptions.draggableCell
                  ? {}
                  : provided.dragHandleProps)}
              >
                {options.draggableRows &&
                  options.draggableRowsOptions.draggableCell && (
                    <this.props.components.Cell
                      value={options.draggableRowsOptions.dragCellContent}
                      columnDef={{
                        tableData: {
                          width: options.draggableRowsOptions.dragCellWidth,
                        },
                      }}
                      {...provided.dragHandleProps}
                    />
                  )}
                {renderColumns}
              </TableRow>
            );
          }}
        </Draggable>
        {this.props.data.tableData &&
          this.props.data.tableData.showDetailPanel && (
            <TableRow
            // selected={this.props.index % 2 === 0}
            >
              <TableCell
                size={size}
                colSpan={renderColumns.length}
                padding="none"
              >
                {this.props.data.tableData.showDetailPanel(this.props.data)}
              </TableCell>
            </TableRow>
          )}
        {this.props.data.tableData.childRows &&
          this.props.data.tableData.isTreeExpanded &&
          this.props.data.tableData.childRows.map((data, index) => {
            if (data.tableData.editing) {
              return (
                <this.props.components.EditRow
                  columns={this.props.columns.filter((columnDef) => {
                    return !columnDef.hidden;
                  })}
                  components={this.props.components}
                  data={data}
                  icons={this.props.icons}
                  localization={this.props.localization}
                  getFieldValue={this.props.getFieldValue}
                  key={index}
                  mode={data.tableData.editing}
                  options={this.props.options}
                  isTreeData={this.props.isTreeData}
                  detailPanel={this.props.detailPanel}
                  onEditingCanceled={onEditingCanceled}
                  onEditingApproved={onEditingApproved}
                  errorState={this.props.errorState}
                />
              );
            } else {
              return (
                <this.props.components.Row
                  {...this.props}
                  data={data}
                  index={index}
                  key={index}
                  level={this.props.level + 1}
                  path={[...this.props.path, index]}
                  onEditingCanceled={onEditingCanceled}
                  onEditingApproved={onEditingApproved}
                  hasAnyEditingRow={this.props.hasAnyEditingRow}
                  treeDataMaxLevel={treeDataMaxLevel}
                  errorState={this.props.errorState}
                />
              );
            }
          })}
      </>
    );
  }
}

MTableBodyRow.defaultProps = {
  actions: [],
  index: 0,
  data: {},
  options: {},
  path: [],
};

MTableBodyRow.propTypes = {
  actions: PropTypes.array,
  icons: PropTypes.any.isRequired,
  index: PropTypes.number.isRequired,
  data: PropTypes.object.isRequired,
  detailPanel: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.object, PropTypes.func])),
  ]),
  hasAnyEditingRow: PropTypes.bool,
  options: PropTypes.object.isRequired,
  onRowSelected: PropTypes.func,
  path: PropTypes.arrayOf(PropTypes.number),
  treeDataMaxLevel: PropTypes.number,
  getFieldValue: PropTypes.func.isRequired,
  columns: PropTypes.array,
  onToggleDetailPanel: PropTypes.func.isRequired,
  onRowClick: PropTypes.func,
  onEditingApproved: PropTypes.func,
  onEditingCanceled: PropTypes.func,
  errorState: PropTypes.oneOfType([PropTypes.object, PropTypes.bool]),
};
```

**Comment by dekelb** [comment]
@Leocete Thanks for your support here. Greatly appreciated!

Actually it work as expected, the issue is with the structure of the function.
It should be:
```
  rowStyle: (rowData) => ({
    backgroundColor: 'red'
  }),
```

Or:
```
  rowStyle: (rowData) => {
    return {
      backgroundColor: 'red'
    };
  }
```

Otherwise the returned value is not an object.

**Comment by Leocete** [comment]
@dekelb, sorry that's my bad :)
I've deleted my previous comment

**Comment by dekelb** [comment]
@Leocete sure, np. Thanks for double checking everything here.

Just to make sure - is there still something that doesn't work as expected?

**Comment by Leocete** [comment]
@dekelb thank you for your efforts! 

I can see the following error in the console created by `Draggable` component, you can see it on demo page:

```
Warning: React does not recognize the `errorState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `errorstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in td (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))
    in WithStyles(ForwardRef(TableCell)) (created by MTableCell)
    in MTableCell (created by MTableBodyRow)
    in tr (created by ForwardRef(TableRow))
    in ForwardRef(TableRow) (created by WithStyles(ForwardRef(TableRow)))
    in WithStyles(ForwardRef(TableRow)) (created by Draggable)
```

Do you have any idea what it could be?

**Comment by dekelb** [comment]
@Leocete looks like this is already fixed in master, so I just pulled from master and no more warnings here.

**Comment by mbrn** [comment]
Hi @dekelb 

Thanks for your effort. But i can't merge this pr. It contains a lot of changes. We will start to a big refactor, testing progress. So i won't accept big changes on code. We will implement this feature later. Thanks for your understanding.

**Comment by kgstew** [comment]
That's sad to hear @mbrn. This means that adding this functionality to an existing implementation will require forking your repository or looking for an alternative solution. Will your future refactor allow for including this library by composition rather than needing to bake a single dnd tool into the code base?

**Comment by dekelb** [comment]
@mbrn - I completely agree with @kgstew.
Moreover - I must say that imho this is not the best way to manage open source projects.

This PR has been open for more than a month, during this time the community (and contributors to this project) gave their feedback, requested changes, did QA and requested to fix conflicts (also your request) in order to make sure this PR will get in, and the response after all that effort is "we are not going to add this because this is a big change".

Handling open source projects require agility and support changes to code. This is why we have the community, this is why we have supporters. When a new bug arise - we fix it. When there are issues - we take care of them.

The reason it was important for me to add the different drag&drop options (columns/rows/row-cell) as part of the working demo was to ensure that current behaviour will not break, and give a very easy way for other people to check it.

The original request to add rows d&d (#1219) is almost 1 year old. During this time that request got 45 reactions and, 35 comments (most of them are +1), it still has the "help wanted" label, and the "waiting for author" label was there in the past (replaced with "help wanted").

If this project does not support new features from the community - it's completely ok. This is part of the open-source community, and it's up to the main maintainer of the library to make such decision. However - it's really important to say so in order to make sure other people will not spend their time on it (and also - people who decide to choose this library will understand what they are getting into).

Are able to provide an estimate on when this feature will get in? "Sometime in the future" is problematic, and if this project does not support new PRs - this might affect other developers and might cause people to just fork this lib and start a new project.

I can share that from where I stand - if this feature will not be merged soon - I might be forced to start a new material table project (might be a fork of this one, might be starting something completely new), mostly because I really need this feature.

Will appreciate your reply here, and thanks for taking the time to read my comments.

**Comment by Leocete** [comment]
@dekelb, I 100% agree with every your word
I've already forked the project and working with your project copy, cause my team and client have been waiting for d'n'd feature for a long time and its never been forked.

**Comment by LeanderCoevoet** [comment]
@Leocete same over here. I made 2 pr dependent on this with extra DnD features. I have also forked it because there was no reaction/live from thé maintainers of this project.

**Comment by checklist** [comment]
Anyone has a working fork of this project with DnD?

**Comment by dekelb** [comment]
> Anyone has a working fork of this project with DnD?

Unfortunately no.
Feel free to fork my branch (https://github.com/dekelb/material-table/tree/feature/rows-dnd) and use it.

If you prefer to just use my fork - you can `npm install` it:
```npm install dekelb/material-table#feature/rows-dnd```

Or if you prefer to add this directly to your `package.json` file you can use the git-notation:

```
  "dependencies": {
    ...
    "material-table": "github:dekelb/material-table#feature/rows-dnd",
    ...
  },
```

If you need there is a live-working example there (just run the server and you will see).

**Comment by checklist** [comment]
> > Anyone has a working fork of this project with DnD?
> 
> Unfortunately no.
> Feel free to fork my branch (https://github.com/dekelb/material-table/tree/feature/rows-dnd) and use it.
> 
> If you prefer to just use my fork - you can `npm install` it:
> `npm install dekelb/material-table#feature/rows-dnd`
> 
> Or if you prefer to add this directly to your `package.json` file you can use the git-notation:
> 
> ```
>   "dependencies": {
>     ...
>     "material-table": "github:dekelb/material-table#feature/rows-dnd",
>     ...
>   },
> ```
> 
> If you need there is a live-working example there (just run the server and you will see).

Thanks a lot! I just got your code to work beautifully! Would have been nice if the repo owner would have used it. These days, DnD is quite a necessity and without it, the lib is not that useful. Luckily with open source, we have people like you!

:-)

**Comment by naimbouallagui** [comment]
@dekelb  thanks for sharing your solution, but it doesn't work for me the  draggableRows option in my project even i put it true (just a simple exemple) !!

**Comment by jepc00ld3v** [comment]
> > Anyone has a working fork of this project with DnD?
> 
> Unfortunately no.
> Feel free to fork my branch (https://github.com/dekelb/material-table/tree/feature/rows-dnd) and use it.
> 
> If you prefer to just use my fork - you can `npm install` it:
> `npm install dekelb/material-table#feature/rows-dnd`
> 
> Or if you prefer to add this directly to your `package.json` file you can use the git-notation:
> 
> ```
>   "dependencies": {
>     ...
>     "material-table": "github:dekelb/material-table#feature/rows-dnd",
>     ...
>   },
> ```
> 
> If you need there is a live-working example there (just run the server and you will see).

After installing your fork, I get Can't resolve 'material-table' error when compiling

**Pull request closed without merging**
