### PR TITLE
Fix NPM7 Peer Dependencies

### PR DESCRIPTION
**Pull request by clytras**
## Related Issue

#2720 #2730

## Description

Add major version pin for `@date-io/core` and `@material-ui/core` plus `^16.8.4 || ^17.0.0` for `react` and `react-dom`.

### CODE REVIEW

**Comment by rkeene** [comment]
Also fixes #2817

**Comment by wilomgfx** [comment]
This is needed ASAP, preventing me to update to npm@7 :(

**Comment by templar11** [comment]
Unable to install material-table on a clean project. Kindly apply the fix please

**Comment by CometS1** [comment]
This is also causing me issues with being unable to install, please apply this fix

**Comment by 1ur11** [comment]
Would be nice to have this ASAP.

**Review by mbrn — APPROVED** [review]
Thanks for PR

**Comment by clytras** [comment]
> Thanks for PR

You're welcome Mehmet. Nice you see you're back 💪

**Comment by PathToLife** [comment]
Seems this PR doesn't fix React 17 still

https://github.com/mbrn/material-table/blob/42d966eacdbe47cd176f9c5c68e3d97b126b489e/package.json#L79

From limited knowledge of npm..

We see that ` @material-ui/pickers@3.2.2` causes an error when installing on a react 17 project

`npm i material-table@1.69.3`

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.4" from @material-ui/pickers@3.2.2
npm ERR! node_modules/material-table/node_modules/@material-ui/pickers
npm ERR!   @material-ui/pickers@"3.2.2" from material-table@1.69.3
npm ERR!   node_modules/material-table
npm ERR!     material-table@"1.69.3" from the root project
```

**Pull request merged**
