### PR TITLE
#1235: prevent actions icons re-render

### PR DESCRIPTION
**Pull request by kwiatkk1**
## Related Issue
#1235

## Description
Prevent action icons to re-render unconditionally.

## Impacted Areas in Application
* MTableAction

### CODE REVIEW

**Comment by kwiatkk1** [comment]
@mbrn what do you think about @TheGoodSpinach suggestion to make some additional changes within this pull-request? Or do you rather want to keep changes small and to open separate one for it?

**Comment by mbrn** [comment]
> @mbrn what do you think about @TheGoodSpinach suggestion to make some additional changes within this pull-request? Or do you rather want to keep changes small and to open separate one for it?

I prefer small bites :)

**Comment by mbrn** [comment]
Hi @kwiatkk1,

 I tested this pr. It is not working. Please check it again. Especially with editable feature.

**Comment by kwiatkk1** [comment]
Hey @mbrn, thanks for review! You're right!

I've tested only a case in which actions were added manually and they were string/function as described in https://material-table.com/#/docs/features/actions.

But when the `editable` option is used, it adds actions that have `icon` property that is a product of React.createRef. And that is not a string nor function but a Component. 

So I added additional check in a code to handle this. Another option would be to change the way default props are defined, but i assume that it's a way more work.

**Comment by kwiatkk1** [comment]
Thanks for accepting this.

Now time for the issue pointed out by @TheGoodSpinach. I'll deal with it in a separate PR.

**Pull request merged**
