### PR TITLE
Add styled footer row

### PR DESCRIPTION
**Pull request by json2d**
## Related Issue
#27 

## Description
The goal was to add a footer row to the tables that can be styled. The main usecase is to render summary data (like column totals)

## Impacted Areas in Application
adds props `footerData`, `options.footerStyle`, and `column.footerCellStyle`
*

## Additional Notes
I tried to base the implementation off the patterns used in the existing code

### CODE REVIEW

**Comment by json2d** [comment]
forked from `v1.36.6`

**Comment by mbrn** [comment]
Hi @json2d ,

Thanks for contribution. But i will implement this feature later. Firstly i want to make MT more stable.

**Comment by claborier** [comment]
@mbrn Hi ! Do you have an idea about when the feature will be available ? 
Also, thanks for your work ;)

**Comment by thedmeyer** [comment]
> Hi @json2d ,
> 
> Thanks for contribution. But i will implement this feature later. Firstly i want to make MT more stable.

Did you have the time to do this? Many thanks

**Pull request closed without merging**
