### PR TITLE
Update material-ui/core

### PR DESCRIPTION
**Pull request by Domino987**
## Description
This updates material-ui/core to [v4](https://material-ui.com/guides/migration-v3/#migration-from-v3-to-v4) with many updates and a reduced bundle size.

### CODE REVIEW

**Comment by mbrn** [comment]
Hi @Domino987 

material-ui-pickers requires 3.*** version of material-ui/core. So we should wait for it upgrade before.

**Comment by Domino987** [comment]
Did not not see that and it worked for me but of course you are right. Thanks for the quick reply

**Comment by Domino987** [comment]
I just checked and material-ui pickers updated t ov4 4 days ago => https://material-ui-pickers.dev/guides/upgrading-to-v3

**Comment by mbrn** [comment]
Oo, i checked it yesterday but i didnt see it. Alright i will merge this tomorrow. Thanks for contribution

**Comment by mbrn** [comment]
@Domino987 

#622 resolved all issues about upgrading to 4.0.0. Thanks to @timsazon

**Pull request closed without merging**
