### PR TITLE
Feature localize date picker

### PR DESCRIPTION
**Pull request by DamjanSk**
## Related Issue
#531

## Description
Expose @material-ui/pickers props to material table.

## Impacted Areas in Application
List general components of the application that this PR will affect:
* FilterRow, EditRow

## Additional Notes
Example:
```
localization={{
          body: {
            emptyDataSourceMessage: getMessage('label.no.records.to.display'),
            dateTimePickerLocalization: resolvedLocaleMap,
            muiDatePickerProps: {
              okLabel: getMessage('label.ok'),
              cancelLabel: getMessage('label.cancel'),
              clearLabel: getMessage('label.clear'),
            },
          },
        }}
```

### CODE REVIEW

**Comment by siebenrene** [comment]
I was working on a fix as well. When I looked into your changes I'm wondering if you have tested the existing localization functionalities as to my mind there is still a bug that prevents the localization to be passed down to the datePicker component.

In src/components/m-table-edit-row.js

<EditComponent
                key={columnDef.tableData.id}
                 columnDef={cellProps}
                 value={value}
                 **locale={this.props.localization.dateTimePickerLocalization}**

Should be in my mind:

<EditComponent
                key={columnDef.tableData.id}
                 columnDef={cellProps}
                 value={value}
                 **dateTimePickerLocalization**={this.props.localization.dateTimePickerLocalization}**

What is your opinion on that?

**Comment by DamjanSk** [comment]
> 
> 
> I was working on a fix as well. When I looked into your changes I'm wondering if you have tested the existing localization functionalities as to my mind there is still a bug that prevents the localization to be passed down to the datePicker component.
> 
> In src/components/m-table-edit-row.js
> 
> <EditComponent
> key={columnDef.tableData.id}
> columnDef={cellProps}
> value={value}
> **locale={this.props.localization.dateTimePickerLocalization}**
> 
> Should be in my mind:
> 
> <EditComponent
> key={columnDef.tableData.id}
> columnDef={cellProps}
> value={value}
> **dateTimePickerLocalization={this.props.localization.dateTimePickerLocalization}**
> 
> What is your opinion on that?

You are right, I missed that. I updated the pull request.
I thought about changing `locale={this.props.dateTimePickerLocalization}` to `locale={this.props.locale}>` in m-table-edit-field.js, but this makes more sense.

**Comment by Domino987** [comment]
Can you take a look at the merge conflicts, so that this could be merged?

**Comment by mbrn** [comment]
Hi @DamjanSk 

Thanks for your effort. But i think that we should not move props of datepicker inside localization. You can override editcomponent as a workaround until we find a better solution.

**Pull request closed without merging**
