### PR TITLE
respect user styles over inherit width

### LINKED ISSUE #2487: Is it possible to set a minimum width for a column?
We have tables in which not all columns are equally important and would like to make one column significantly wider than the others. Is that possible?

### PR DESCRIPTION
**Pull request by Domino987**
## Related Issue

Fixes #2487

## Description

Custom cell width will be overridden with reducePercentsInCalc but should still be user settable.
This PR fixes that by reordering the overriding the order of spreading.

### CODE REVIEW

**Comment by zeckdude** [comment]
@mbrn Can this please be merged in?

**Comment by spudcud** [comment]
Just started using the table (great job btw) and this is a blocking issue for me convincing people to switch. Any idea on when this will be merged and released?

**Comment by zeckdude** [comment]
@spudcud I switched to 1.64.0 for now and that solved the issue since the bug was introduced after that.

**Comment by spudcud** [comment]
Thanks @zeckdude I'll give that a try.

**Comment by spudcud** [comment]
@mbrn Would it be possible to take a look at this pull request to get it in?

**Comment by kasugaicrow** [comment]
Any news about the possibility to look at this pull request?

**Pull request closed without merging**
