### PR TITLE
Update m-table-filter-row.js

### PR DESCRIPTION
**Pull request by tjavae**
Add
- KeyboardDateTimePicker
- format={columnDef.format}

## Related Issue
Relate the Github issue with this PR using `#`

## Description
Simple words to describe the overall goals of the pull request's commits.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

## Additional Notes
This is optional, feel free to follow your hearth and write here :)

### CODE REVIEW

**Comment by prisis** [comment]
Is something missing so that cant be merge?

I would needing the possibility to change the date/time format.

**Comment by tjavae** [comment]
We add format field in prop-types.js. Which I have been submit in other request along with this request.

**Comment by tjavae** [comment]
> Is something missing so that cant be merged?
> 
> I would needing the possibility to change the date/time format.

I added on request #916 . Request #918 & #916 go together.

**Comment by mbrn** [comment]
Please merge #916 #917 and #918

**Pull request closed without merging**
