### PR TITLE
Added Feature - Multiple rows update in parallel

### PR DESCRIPTION
**Pull request by admasodaniel**
## Description

This feature will allow to update fields of selected rows (a group of rows) in parallel, for instance:
if you have a group of rows that you want to update a new value to the field "Name" in all of the rows,
with this feature, you can do this easily without changing the same field for each row, again, and again, you only have to do this once.

## Impacted Areas in Application

List general components of the application that this PR will affect:
 - m-table-toolbar
 - m-table-edit-row
 - m-table-header

## Additional Notes

1. Select the rows that you want to update, then click on "Edit selected rows" button at the top right corner.
Screen Shot 2020-08-26 at 3 45 51 PM

2. Edit some of the fields, and the relevant fields of other selected rows will update in parallel.
Screen Shot 2020-08-26 at 3 43 19 PM

### CODE REVIEW

**Comment by amitnandi123** [comment]
in which version I will get this feature .

**Comment by Svish** [comment]
@amitnandi123 What in the world are you tagging me for?

**Comment by amitnandi123** [comment]
I am looking for this feature Multiple rows update in parallel . and I am now to github I just got your name as a suggestion  .

**Comment by Svish** [comment]
@amitnandi123 Don't tag random people you're not 100% sure actually has anything to do with what you're asking about. It's rude and annoying. I'm not on the MaterialUI team, and this issue has nothing to do with me at all.

**Pull request closed without merging**
