### PR TITLE
[Feature] Add feature to hide actions based on a function with rowDat…

### PR DESCRIPTION
**Pull request by GabriMagic**
…a attributes

## Related Issue

#2483

## Description

Add feature to hide actions with a function in adittion to a simple boolean.

## Related PRs

N/A

## Impacted Areas in Application

List general components of the application that this PR will affect:

- MTableAction

## Additional Notes

I would like to help more this library so I liked to add this feature, it could be added also with "disabled" property. Btw, I wish you could accept it and release the functionality so I could update to the last version.

Also I don't know why the "Prettier CLI" failed, if you could explain that to it would be nice, thanks

### CODE REVIEW

**Comment by GabriMagic** [comment]
Morning, I would like to know if I should change something to the pipeline pass successfully, thanks in advance

**Comment by KannarFr** [comment]
@GabriMagic can you check this is working if the selection option is true? It seems function actions are not run if the selection option is set to true.

**Comment by KannarFr** [comment]
@GabriMagic can you confirm that this is not working is the selection option is set to true?

**Comment by GabriMagic** [comment]
"It works", and in this case I think the behaviour is on the hand of the user. For instance...

Having this table and this actions
```actions={[
  {
    icon: "save",
    tooltip: "Save",
    onClick: (E, rowData) => alert(rowData.name),
    hidden: (rowData) => rowData.name === "A2"
  },
  {
    icon: "home",
    tooltip: "Home",
  onClick: (E, rowData) => alert(rowData.name),
    hidden: false,
  },
  {
    icon: "remove",
    tooltip: "Remove",
    onClick: (E, rowData) => alert(rowData.name),
    hidden: true,
  },
]}
```

image

The "save" option won't be available when the name is "A2" so in this case works normally.

---

When we add the "selection" option:
image

You have all actions because the rowData in this case is an Array, it can be easily modified with this action. As I think, the hidden condition for actions are in the hand of the user, if you use the "selection" mode, you should know the rowData will be an array, and you could disable an action when meet a certain condition, or just evaluate the values on the "onChange" or "onSelect".

So I think the feature only add the option to manage the "rowData" inside the **hidden()** mnethod.

```
{
  icon: "save",
  tooltip: "Save",
  onClick: (E, rowData) => alert(rowData.name),
  hidden: (rowData) => {
    if (rowData instanceof Array) {
      return !!rowData.find(data => data.name === "A2");
    } else {
      return rowData.name === "A2";

    }
  },
},
```

**Comment by KannarFr** [comment]
@GabriMagic I fixed a typo on my previous message, can you try to enable the selection: true option which is not available on your example (of answer I received) cf. https://github.com/mbrn/material-table/issues/609#issuecomment-716973634.

**Comment by GabriMagic** [comment]
I add the example with the selection option as "true", you can clone the branch and test it on your own.

**Comment by WildOsk** [comment]
great contribution @GabriMagic I hope it can be implemented ASAP @mbrn

**Comment by GabriMagic** [comment]
Thanks @WildOsk 😄

**Comment by GabriMagic** [comment]
Will this feature reviewed?

**Pull request closed without merging**
