### PR TITLE
fix(fusionjs): Fix material-core import failures

### PR DESCRIPTION
**Pull request by pandomic**
## Related Issue
When using Fusion framework and material-ui installed as a plugin some of Material-table's components fail to load `withStyles` and `material-ui/core` with `Uncaught TypeError: Cannot read property 'call' of undefined` error when calling `_interopRequireDefault(require('@material-ui/core'))` and `_interopRequireDefault(require('@material-ui/core/styles/withStyles'))`.

## Description
After hours spent to figure out the issue, I decided to try to replace `/withStyles` imports to `{ withStyles }`, and any `import {...} from '../core'` to explicit `import Something from '.../core/Something'` and then it started working again.

I may guess that inconsistent imports are somehow affecting the produced code which can't be solved by the Webpack configuration bundled with Fusion framework.

### CODE REVIEW

**Comment by mbrn** [comment]
@pandomic Can you resolve conflicts please.

**Comment by pandomic** [comment]
@mbrn thank you, sure, will take try to solve them in the next day or two

**Comment by pandomic** [comment]
@mbrn please find an updated version with resolved conflicts 😉

**Comment by mbrn** [comment]
Please resolve conflicts

**Comment by cyw233** [comment]
I have encountered the same issue today. When will the pr be merged into master?

**Comment by pandomic** [comment]
@mbrn I resolved the conflicts, however, now I'm getting another error with hooks due to some recent changes (I guess). I'll try to debug and eliminate the issue once I have time for that.

image

cc @cyw233

**Comment by mbrn** [comment]
> @mbrn I resolved the conflicts, however, now I'm getting another error with hooks due to some recent changes (I guess). I'll try to debug and eliminate the issue once I have time for that.
> 
> image
> (Ignore wrapping components, I reproduced the same thing with empty project, but decided to re-try on a real one)
> 
> cc @cyw233

I am waiting for your solution to merge.

**Comment by mbrn** [comment]
I am closing this. You can reopen it after completing all changes.

**Pull request closed without merging**
