### PR TITLE
Add support for Formik

### PR DESCRIPTION
**Pull request by truongtv22**
## Related Issue
Relate the Github issue with this PR using `#`

## Description
Simple words to describe the overall goals of the pull request's commits.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

## Additional Notes
This is optional, feel free to follow your hearth and write here :)

### CODE REVIEW

**Comment by truongtv22** [comment]
Example
```import React, { Component } from 'react';
import { Formik, Field, getIn } from 'formik';

import MaterialTable, { FormField, MTableEditRow } from 'material-table';

const FormikField = props => (
  <Field
    name={props.columnDef.field}
    render={({ field, form }) => {
      const { name } = field;
      const { errors, setFieldValue } = form;

      const showError = !!getIn(errors, name);

      return (
        <FormField
          {...props}
          {...field}
          error={showError}
          onChange={newValue => setFieldValue(name, newValue)}
        />
      );
    }}
  />
);

const MuiTableEditRow = ({ onEditingApproved, ...props }) => (
  <Formik
    initialValues={props.data}
    onSubmit={newData => {
      delete newData.tableData;
      onEditingApproved(props.mode, newData, props.data);
    }}
    render={({ submitForm }) => (
      <MTableEditRow {...props} onEditingApproved={submitForm} />
    )}
  />
);

class App extends Component {
  render() {
    return (
      <MaterialTable
        data={[
          { id: 1, firstName: 'ax', firstName: 'Baran' }
        ]}
        columns={[
          { title: 'First Name', field: 'firstName' },
          { title: 'Last Name', field: 'lastName' },
        ]}
        editable={{
          onRowAdd: (newData) => new Promise((resolve, reject) => {
            resolve();
          }),
        }}
        components={{
          EditRow: MuiTableEditRow,
          FormField: FormikField
        }}
      />
    )
  }
}
```

**Comment by mbrn** [comment]
Hi @truongtv22 ,

I merged but made some changes:

1. rename the FormField as EditField on components to be override. 
2. add editComponent to columns. So developer override just one columns edit component instead of overriding all.

**Comment by truongtv22** [comment]
Hi @mbrn, I hope you update the version soon

**Comment by mbrn** [comment]
@truongtv22 ,

I will update version today after merging all prs and resolve a few issue.

**Comment by p45mark** [comment]
Is there a working example of using material-table with Formik?

**Comment by Flash619** [comment]
> Is there a working example of using material-table with Formik?

@p45mark Were you able to figure out a good way to implement Formik? I'm trying but it's not going great. I can make a Formik field component, and pass it to `editComponent`, but then my formik field component will error out because it has required props of form and field. 

```typescript
{
            title: 'Vendor',
            field: 'id',
            editComponent: props => <FormikVendorSelect {...props} />, //Missing form and field props.
        },
```

**Comment by rffensick** [comment]
The whole list of changes:
1. FormField in components renamed to EditField
2. FormField from material-table renamed to MTableEditField

**Comment by rffensick** [comment]
> > Is there a working example of using material-table with Formik?
> 
> @p45mark Were you able to figure out a good way to implement Formik? I'm trying but it's not going great. I can make a Formik field component, and pass it to `editComponent`, but then my formik field component will error out because it has required props of form and field.
> 
> ```ts
> {
>             title: 'Vendor',
>             field: 'id',
>             editComponent: props => <FormikVendorSelect {...props} />, //Missing form and field props.
>         },
> ```

You need wrap you component to Field, like in the example above.

**Comment by mrjdavidfg** [comment]
@truongtv22 
Hi, Do you remember why you remove this property `tableData`?
```
    onSubmit={newData => {
      delete newData.tableData; // <--- tableData
      onEditingApproved(props.mode, newData, props.data);
    }}
```
Its trowing error (tableData undefined) when deleting a row and also when updating a row when nothing was modified. Removing that line fix those errors.

**Comment by truongtv22** [comment]
> @truongtv22
> Hi, Do you remember why you remove this property `tableData`?
> 
> ```
>     onSubmit={newData => {
>       delete newData.tableData; // <--- tableData
>       onEditingApproved(props.mode, newData, props.data);
>     }}
> ```
> 
> Its trowing error (tableData undefined) when deleting a row and also when updating a row when nothing was modified. Removing that line fix those errors.

Hi, You can see it here
https://github.com/mbrn/material-table/blob/e0c2362c24f6dbb1ce61b801fb12608c71f5e2e0/src/components/m-table-edit-row.js#L125

**Comment by truongtv22** [comment]
Example updated
```import React from "react";
import { Formik, Field, getIn } from "formik";

import MaterialTable, { MTableEditRow, MTableEditField } from "material-table";

const FormikEditRow = ({ onEditingApproved, ...props }) => {
  return (
    <Formik
      initialValues={props.data}
      onSubmit={newData => {
        if (props.mode === "add" || props.mode === "update")
          delete newData.tableData;
        onEditingApproved(props.mode, newData, props.data);
      }}
    >
      {({ submitForm }) => (
        <MTableEditRow {...props} onEditingApproved={submitForm} />
      )}
    </Formik>
  );
};

const FormikEditField = props => (
  <Field name={props.columnDef.field}>
    {({ field, form }) => {
      const { name } = field;
      const { errors, setFieldValue } = form;

      const showError = !!getIn(errors, name);

      return (
        <MTableEditField
          {...props}
          {...field}
          error={showError}
          onChange={newValue => setFieldValue(name, newValue)}
        />
      );
    }}
  </Field>
);

export default function App() {
  const [data, setData] = React.useState([
    { id: 1, firstName: "Ta", lastName: "Truong" }
  ]);

  return (
    <MaterialTable
      data={data}
      columns={[
        { title: "First Name", field: "firstName" },
        { title: "Last Name", field: "lastName" }
      ]}
      editable={{
        onRowAdd: newData =>
          new Promise((resolve, reject) => {
            setData([...data, newData]);

            resolve();
          }),
        onRowUpdate: (newData, oldData) =>
          new Promise((resolve, reject) => {
            const dataUpdate = [...data];
            const index = oldData.tableData.id;
            dataUpdate[index] = newData;
            setData([...dataUpdate]);

            resolve();
          }),
        onRowDelete: oldData =>
          new Promise((resolve, reject) => {
            const dataDelete = [...data];
            const index = oldData.tableData.id;
            dataDelete.splice(index, 1);
            setData([...dataDelete]);

            resolve();
          })
      }}
      components={{
        EditRow: FormikEditRow,
        EditField: FormikEditField
      }}
      initialFormData={{
        firstName: "",
        lastName: ""
      }}
    />
  );
}
```

**Comment by awvala** [comment]
Thank you, this is a huge help!  I'm attempting to use Formik with custom inputs (TextField and Select Material components), but the component values are either blank on new or result in an error when attempting to edit the default data values.  I feel like I'm missing something obvious here.

```
export default function ApplicationMaterialTable(props) {

    const [data, setdata] = useState([
        { applicationName: "Test", flowrate: 2, waterrate: "Reg" },
        { applicationName: "Test2", flowrate: 10, waterrate: "Reg" },
    ]);

    const disableStep = props.completed[1] ? "disabled" : null;
    const disableForm = props.completed[1] ? true : false;
    const classes = useStyles();

    return (
        <MaterialTable
            title="Applications"
            isEditable={disableForm}
            data={data}
            options={{
                search: false,
                paging: false
            }}
            icons={tableIcons}
            columns={[
                {
                    title: 'Application Name',
                    field: 'applicationName',
                    editComponent: props => (
                        <TextField
                            disabled={disableStep}
                            className={classes.fieldStyle}
                            name="applicationName"
                            label="Name"
                            id="applicationName"
                            variant="outlined"
                            size="small"
                            required
                            value={props.value}
                            onChange={e => props.onChange(e.target.value)}
                        />
                    )
                },
                {
                    title: 'Flow Rate',
                    field: 'flowrate',
                },
                {
                    title: 'Water Rate',
                    field: 'waterrate',
                }
            ]}
            editable={{
                onRowAdd: newData =>
                    new Promise((resolve, reject) => {
                        setdata([...data, newData]);

                        resolve();
                    }),
                onRowUpdate: (newData, oldData) =>
                    new Promise((resolve, reject) => {
                        const dataUpdate = [...data];
                        const index = oldData.tableData.id;
                        dataUpdate[index] = newData;
                        setdata([...dataUpdate]);

                        resolve();
                    }),
                onRowDelete: oldData =>
                    new Promise((resolve, reject) => {
                        const dataDelete = [...data];
                        const index = oldData.tableData.id;
                        dataDelete.splice(index, 1);
                        setdata([...dataDelete]);

                        resolve();
                    })
            }}
            components={{
                EditRow: FormikEditRow,
                EditField: FormikEditField
            }}
            initialFormData={{
                applicationName: "",
                flowrate: "",
                waterrate: ""
            }}
        />
    );
```

Error after submitting change to applicationName field:
componentError

**Comment by truongtv22** [comment]
> > const showError = !!getIn(errors, name);
> 
> What's the purpose of `!!` at `!!getIn(errors, name);` ?
> 
> I believe it is a typo for `!getIn(errors, name);` or should it be `getIn(errors, name);`?
> 
> by the way, thanks a lot for this example. Helped me a lot!

Hi @LFabre 
Because `getIn(errors, name)` returns a value of type **string**, and the type of prop **error** is a **boolean**.
You can refer to [here](https://material-ui.com/api/text-field/#props)

**Comment by truongtv22** [comment]
Hi @awvala, I tried making an example hoping to help you
https://codesandbox.io/s/material-table-formik-8fzmc

**Comment by awvala** [comment]
Thank you so much for your time putting this together! @truongtv22 !  This was incredibly helpful merging Formik, Yup, Material-table, and a material stepper together.  I'll paste a snippet of code below for anyone in a similar scenario.  This project is combining Material-Table, Yup, Formik, and a Material stepper.

```
import React, { useState, forwardRef } from 'react';
import { makeStyles } from '@material-ui/core/styles';
import { createMuiTheme, ThemeProvider } from '@material-ui/core/styles';

import {
    TextField,
    MenuItem,
    FormControl,
    FormHelperText,
    Select
} from '@material-ui/core';

import MaterialTable, { MTableEditRow, MTableEditField } from "material-table";
import { Formik, Field, getIn } from 'formik';
import * as yup from "yup";


const applicationSchema = yup.object().shape({
    applicationName: yup.string().required("Required"),
    flowrate: yup.number().positive("Must be a positive number").integer("Decimals not allowed").required("Required"),
    waterrate: yup.string().required("Required"),
})

// Overrides default styling of table cells and Select components in Material-UI
let theme = createMuiTheme({
    overrides: {
        MuiTableCell: {
            root: {
                padding: "10px"
            }
        },
        MuiInputBase: {
            root: {
                fontSize: "small"
            }
        },
        MuiSelect: {
            root: {
                paddingTop: "10.5px",
                paddingBottom: "10.5px"
            }
        }
    },
});

const useStyles = makeStyles(theme => ({
    sectionBox: {
        paddingLeft: "0px",
        paddingRight: "0px",
        marginRight: "-22px",
        marginLeft: "-15px"
    },
    sectionButtonBox: {
        marginBottom: theme.spacing(2),
    },
    fieldStyle: {
        width: "98%",
        minWidth: 100
    },
    numberFieldStyle: {
        minWidth: 75
    },
    button: {
        margin: theme.spacing(1)
    },
    stepbutton: {
        marginTop: theme.spacing(1),
        marginRight: theme.spacing(1),
    },
    MuiStepContent: {
        paddingLeft: "10px",
        paddingRight: "0px",
    },
}));

const waterOptions = [
    "Reg",
    "Temp/Hot",
    "RO",
    "Other"
];

const FormikEditRow = ({ onEditingApproved, ...props }) => {
    return (
        <Formik
            initialValues={props.data}
            validationSchema={applicationSchema}
            onSubmit={data => {
                if (props.mode === "add" || props.mode === "update") {
                    const { tableData, ...newData } = data;
                    onEditingApproved(props.mode, newData, props.data);
                } else {
                    onEditingApproved(props.mode, data, props.data);
                }
            }}
        >
            {({ submitForm }) => (
                <MTableEditRow {...props} onEditingApproved={submitForm} />
            )}
        </Formik>
    );
};

const FormikEditField = props => (
    <Field name={props.columnDef.field}>
        {({ field, form }) => {
            const { name } = field;
            const { errors, setFieldValue } = form;

            const showError = !!getIn(errors, name);

            return (
                <div>
                    <MTableEditField
                        {...props}
                        {...field}
                        error={showError}
                        onChange={newValue => setFieldValue(name, newValue)}
                    />
                    {errors[field.name] && (
                        <div style={{ color: "#f44336", clear: "both" }}>{errors[field.name]}</div>
                    )}
                </div>
            );
        }}
    </Field>
);

const tableStepperComponent= (props) => {
    const classes = useStyles();

/// parent props

    const [data, setdata] = useState(
        props.appValues
    );

    let varEditFields = props.completed[activeStep] ? 'never' : 'always';

    return (
        <ThemeProvider theme={theme}>
            <section className={classes.sectionBox}>
                <MaterialTable
                    title="Applications"
                    data={data}
                    options={{
                        search: false,
                        paging: false,
                        actionsColumnIndex: -1,
                        addRowPosition: "first",
                        actionsCellStyle: {
                            paddingLeft: "5px",
                            paddingRight: "5px"
                        }
                    }}
                    icons={tableIcons}
                    columns={[
                        {
                            title: 'Application Name',
                            field: 'applicationName',
                            editable: varEditFields,
                            editComponent: props => (
                                <Field name={props.columnDef.field}>
                                    {({ field, form }) => {
                                        const { name } = field;
                                        const { errors, setFieldValue } = form;
                                        const showError = !!getIn(errors, name);
                                        return (
                                            <TextField
                                                {...field}
                                                className={classes.fieldStyle}
                                                variant="outlined"
                                                size="small"
                                                placeholder="Name"
                                                error={showError}
                                                onChange={event => setFieldValue(name, event.target.value)}
                                                helperText={errors.applicationName ? errors.applicationName : null}
                                            />
                                        );
                                    }}
                                </Field>
                            )
                        },
                        {
                            title: 'Flow Rate',
                            field: 'flowrate',
                            editable: varEditFields,
                            editComponent: props => (
                                < Field name={props.columnDef.field}>
                                    {({ field, form }) => {
                                        const { name } = field;
                                        const { errors, setFieldValue } = form;
                                        const showError = !!getIn(errors, name);
                                        return (
                                            <TextField
                                                {...field}
                                                className={classes.numberFieldStyle}
                                                variant="outlined"
                                                size="small"
                                                placeholder="Flow"
                                                type="number"
                                                error={showError}
                                                onChange={event => setFieldValue(name, event.target.value)}
                                                helperText={errors.flowrate ? errors.flowrate : null}
                                            />
                                        );
                                    }}
                                </Field>
                            )
                        },
                        {
                            title: 'Water Rate',
                            field: 'waterrate',
                            editable: varEditFields,
                            editComponent: props => (
                                <Field name={props.columnDef.field}>
                                    {({ field, form }) => {
                                        const { name } = field;
                                        const { errors, setFieldValue } = form;
                                        const showError = !!getIn(errors, name);
                                        return (
                                            <FormControl>
                                                <Select
                                                    {...field}
                                                    variant="outlined"
                                                    size="small"
                                                    error={showError}
                                                    onChange={event => setFieldValue(name, event.target.value)}
                                                >
                                                    <MenuItem value="">
                                                        <em>Water</em>
                                                    </MenuItem>
                                                    {
                                                        waterOptions.map((item) => (
                                                            <MenuItem value={item}>{item}</MenuItem>
                                                        ))
                                                    }
                                                </Select>
                                                <FormHelperText>{errors.waterrate ? errors.waterrate : null}</FormHelperText>
                                            </FormControl>
                                        );
                                    }}
                                </Field>
                            )
                        }
                    ]}
                    editable={{
                        onRowAdd: newData =>
                            new Promise((resolve, reject) => {
                                setdata([...data, newData]);

                                resolve();
                            }),
                        onRowUpdate: (newData, oldData) =>
                            new Promise((resolve, reject) => {
                                const dataUpdate = [...data];
                                const index = oldData.tableData.id;
                                dataUpdate[index] = newData;
                                setdata([...dataUpdate]);

                                resolve();
                            }),
                        onRowDelete: oldData =>
                            new Promise((resolve, reject) => {
                                const dataDelete = [...data];
                                const index = oldData.tableData.id;
                                dataDelete.splice(index, 1);
                                setdata([...dataDelete]);

                                resolve();
                            })
                    }}
                    components={{
                        EditRow: FormikEditRow,
                        EditField: FormikEditField
                    }}
                    initialFormData={{
                        applicationName: "",
                        flowrate: "",
                        waterrate: ""
                    }}
                />


  /// Stepper component

export default tableStepperComponent;
```

Which results in:
example

**Comment by szediwy** [comment]
Is the field definition 'initialFormData' for the typescript types missing? I am not able to use it.

**Pull request merged**
