### PR TITLE
Add localization for label on select

### PR DESCRIPTION
**Pull request by TatiTheFreaK**
## Related Issue
#371 

## Description
Add localization for label on select

## Impacted Areas in Application
pagination

### CODE REVIEW

**Comment by TatiTheFreaK** [comment]
Where should I put the proptypes, since I included the string inside the pagination object?

**Comment by mbrn** [comment]
search for "MaterialTable.propTypes = {" in material-table.js

**Comment by TatiTheFreaK** [comment]
image
I've put the prop inside the pagination object, so I wouldn't be able to insert the proptype here... Unless you want me to put it out of the object

**Comment by mbrn** [comment]
Thanks for contribution @TatiTheFreaK . I will publish it asap.

**Pull request merged**
