### PR TITLE
support export all remote data

### PR DESCRIPTION
**Pull request by chunkitmax**
## Related Issue

N/A

## Description

Currently, the default export functions export data loaded on the current page.
Even when `exportAllData: true`, the table exports the rendered remote data only (on the current page).
This patch allows it to get all remote data for export.

## Additional Notes

Not sure if async/await is allow to use :)

### CODE REVIEW

**Comment by chunkitmax** [comment]
Hi @ollyrowe, thank you for your suggestion. Yes, it should send a single request for all data.

**Review by robincsamuel — APPROVED** [review]

**Comment by ollyrowe** [comment]
@Domino987, is there any progress with this?

**Comment by prevostc** [comment]
Nice addition !

**Comment by robincsamuel** [comment]
Won't fix?

**Comment by Domino987** [comment]
Hello @robincsamuel Since mbrn is afk, we moved to material-table/core to support this library further. Please update to the new lib and see if it works for you. Thank you

**Pull request closed without merging**
