### PR TITLE
Data age

### PR DESCRIPTION
**Pull request by devel0**
## Related Issue
Relate the Github issue with this PR using #500 

## Description
dataAge table prop if omitted works in a backward compatible way
if specified a value more than -1 it can be used to communicate the table that datasource changed causing render to be accepted

## Impacted Areas in Application
List general components of the application that this PR will affect:

- render performance

## Additional Notes
follow [sandbox](https://codesandbox.io/s/github/devel0/repros/tree/b0668933257b011f03bfbe34115476b9e78a3ac5/material-table/test01) shows how this works in a backward mode and then using dataAge to fire render on datasource changes

Peek 2019-04-24 19-08x

### CODE REVIEW

**Comment by devel0** [comment]
there is a minor issue that cause table not refresh first time `dataAge` is set; to solve that just increase dataAge twice and table refresh instantly; it may related to the react lifecycle render, shouldcomponent update, etc.

At the moment I using this PR in a project where dataAge is attached to a redux prop; updating dataAge after item subsequently to any save or items loaded make it work as expected with no more refresh if changing state for other controls external to the table.

**Comment by devel0** [comment]
I converted invalidated from boolean to a number in order to allow searchText render correctly; without it it lost digited chars

**Comment by mbrn** [comment]
Hi @devel0 

Thanks for contribution. But I am not sure, this is the effective way to solve this problem. I will take a look at your solution again. I am merging prs by order.

**Comment by devel0** [comment]
Hi @mbrn ,
Yes the solution provided with PR is more a workaround but I pulled just to let you know one of possible approach and to have an alternative when a better solution coming up to have a comparision.
Btw, I'm not very experienced in js so I could wrong, but I think that the use of a support variable to allow user communicate that datasource changed should a feasible way. Another way like in c# could be using an Observable Collection ( here a [package](https://www.npmjs.com/package/observable-collection) ) to provide the datasource so that material table if states ds instanceof that can listen to datasource changes to "invalidate" the view automatically without having the user to worry about, but I don't know if such solution could results in a poor performance due to the fact that the observable collection should track changes and more the user should have to enclose its datasource in that and this would be framework constraint addition.
So definitively a solution with something similar to dataAge prop but written more appropriately ( using dataManager ) could not be so a bad approach because at the end the developer knows points where its datasource changes ( on load, on add, delete, update rows activities ) and working on that property shouldn't difficult ( personally I use redux from a global store ).
Thanks you too and others that contributed to this nice component, it's helpful to me.

**Comment by mbrn** [comment]
We can use shouldComponentUpdate instead of a increasing a age variable.

**Pull request closed without merging**
