### PR TITLE
fix change pageSize in remote data mode

### PR DESCRIPTION
**Pull request by ArtemObzhelianskyi**
## Related Issue
Relate the Github issue with this PR using `#`

## Description
Simple words to describe the overall goals of the pull request's commits.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

## Additional Notes
This is optional, feel free to follow your hearth and write here :)

### CODE REVIEW

**Comment by nvtin** [comment]
Why did not nobody look at this PR? It resolved the pageSize issued doing something with data.

**Comment by moshe** [comment]
ping @ChristPetitjean , I'm facing the same issue

**Comment by rrozema12** [comment]
Can we get this merged in? Experiencing this as well

**Comment by bogomya** [comment]
@ChristPetitjean bump

**Comment by enckao** [comment]
Experiencing same issue, expanding a detailPanel on click just reset the pageSizeOptions to default, and I don't know how to get around this issue waiting for this MR to be approuved. If anybody here knows a workaround, you have my attention.

**Comment by ndebeiss** [comment]
Hello
The PR is reverting one of the changes of commit :

https://github.com/orestes22/material-table/commit/6d708f37fa6814c749c69ed6c6e4171c79e624df

solving issue (according to the comment) :

https://github.com/mbrn/material-table/issues/1353

and the PR :

https://github.com/mbrn/material-table/pull/1638/files

also changes that code. It looks complex.

**Comment by mbrn** [comment]
Hi @ArtemObzhelianskyi 

Thanks for your effort. As @ndebeiss explained, we can not merge this pr cause of other side effects. I will try to find another solution.

**Pull request closed without merging**
