### PR TITLE
Add prettier formating

### PR DESCRIPTION
**Pull request by Domino987**
## Description
This PR adds prettier formatting to the project.
All files will be format accordingly to the prettier convention on commit and github actions will format it on opening of a PR.

All fies are initially prettified.

## Impacted Areas in Application
* All js/md files
* .github folder

## Additional Notes
If you want to format on save, install the prettier vs code extension.

### CODE REVIEW

**Comment by dekelb** [comment]
IMHO it's great to add prettier/linter, but it's better to merge such change right after a new version is released. Otherwise there are many PRs that will have conflicts and it is going to be hard to merge them as part of a new release.

The best way is to probably merge as many PRs as possible (before such change), release a new version, and immediate after such release to create new PR with the prettier changes.

**Comment by Domino987** [comment]
That's is true and we just releases a new version. And I will resolve the conflicts tomorrow.

**Comment by dekelb** [comment]
My bad! I didn't notice 1.60 was just release :-) congrats!
I'm pretty sure my PR (#1995) is going to be affected. I can assume others will be too.

**Comment by Domino987** [comment]
It was only a few minutes ago. Once this is merged, it will either rerun the actions by itself or a simple empty commit of yours will run the soon to be added actions, which will prettify you code for yourself, so you do not need to do anything once the action ran.

**Comment by mbrn** [comment]
@Domino987 

Can you resolve conflicts please? I can merge this after 1.62.0

**Comment by Domino987** [comment]
I will tonight

**Comment by Domino987** [comment]
@mbrn Done!

**Pull request merged**
