### PR TITLE
default values for addRow

### PR DESCRIPTION
**Pull request by Paktusin**
## Description
default values for new row Data

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

## Additional Notes
This is optional, feel free to follow your hearth and write here :)

### CODE REVIEW

**Comment by tonyjiang** [comment]
Really really need this feature/fix! Please approve and merge! Many thanks!

**Comment by mbrn** [comment]
Hi @Paktusin 

Thanks for contribution. It is very clear. But we use emptyValue field for different purpose. We may try to find better solution. 

1. add 'initialValue' field to column. value can be primitive type of a function that returns value.
2. Adding two function to editable of table. Such as onBeforeEdit. 

What do you think?

**Comment by rogerclotet** [comment]
Option 1 sounds good :+1:

**Comment by ymoran00** [comment]
Really need this fix....

**Comment by mbrn** [comment]
I added `initialEditValue` to columns.

**Comment by mbrn** [comment]
Published with version 1.45.0

**Comment by Paktusin** [comment]
> Published with version 1.45.0

Thanks!

**Comment by tadstratford** [comment]
Thanks!  This really helps!

**Pull request merged**
