### PR TITLE
set currency as number instead of text

### PR DESCRIPTION
**Pull request by francescovenica**
## Description

Set currency as numeric field

### CODE REVIEW

**Comment by Domino987** [comment]
Hi thanks for the contribution. Can you validate what happens if the field gets cleared? Will there be a 0 or an empty field ?

**Comment by francescovenica** [comment]
Hello I kept the same behaviour of the numeric textfield, if the value is undefined it use an empty string

**Comment by francescovenica** [comment]
ok, I understood what do you mean, with no value it gives NaN, I'll fix it!

**Comment by Domino987** [comment]
Looks better. I'll test it later. Can you remove the demo changes though?

**Comment by francescovenica** [comment]
sure!

**Pull request merged**
