### PR TITLE
Fixed dynamic container sizing for fixedColumns

### PR DESCRIPTION
**Pull request by viral-sh**
## Related Issue

#2240 

## Description

While we have fixedColumns, the container sizing is broken in some cases. This PR fixes those issues

- Fixed column container sizing if any columns are hidden
- Fixed column container sizing when layout changes from "auto" to "fixed" dynamically

From  #2238

- Excluding selection action size from calculation for right fixed column
- added an easy test in demo page
- added width to all columns for fixed layout testing
- organized bottom actions section

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| viral-sh:fix/right-fixed-columns-size | [#2238](https://github.com/mbrn/material-table/pull/2238) |

## Impacted Areas in Application

List general components of the application that this PR will affect:

- Fixed columns container sizing

## Additional Notes

This PR sits on top of #2238

### CODE REVIEW

**Comment by viral-sh** [comment]
@mbrn Any issues/concern in merging this? Anything I can do to help?

**Comment by mbrn** [comment]
> @mbrn Any issues/concern in merging this? Anything I can do to help?

Hi @viral-sh 

I just want to test this pr. Because it calls setState in getProps. This might create a circular setState in some cases. I want to be sure.

**Comment by viral-sh** [comment]
@mbrn Makes sense. Thank you for replying.

**Comment by cdruck** [comment]
Desperately need this PR to be merged .... 1.69.0 is unusable, I need features from 1.68.0 (bulkUpdate) which is also broken, and so I cannot roll back to 1.67.1 ... Waiting on this for a week now :( @mbrn

**Comment by cdruck** [comment]
Actually this doesn't seem to solve the issue that's blocking me. Huh.

**Comment by bdockbockd** [comment]
Is this issued solved?

**Pull request closed without merging**
